[package]
edition = "2021"
name = "libcrux-aesgcm-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.libcrux-aesgcm]
path = ".."

[[bin]]
bench = false
doc = false
name = "encrypt128"
path = "fuzz_targets/encrypt128.rs"
test = false

[[bin]]
bench = false
doc = false
name = "encrypt256"
path = "fuzz_targets/encrypt256.rs"
test = false
