/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/79mbhm8cx0rrgdyj2jfxiq5h7l5cd3km-ocaml4.14.1-eurydice-dirty/bin/eurydice --config ../c.yaml ../../libcrux_sha3.llbc
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef __internal_libcrux_sha3_H
#define __internal_libcrux_sha3_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "internal/core.h"
#include "../libcrux_sha3.h"
#include "eurydice_glue.h"

typedef struct K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t;

#if defined(__cplusplus)
}
#endif

#define __internal_libcrux_sha3_H_DEFINED
#endif
