[target.ml-kem]
cargo = "-p libcrux -p libcrux-platform"
target = "fstar"
include = "-** +libcrux::kem::kyber::** +!libcrux_platform::* -libcrux::hacl::sha3::** -libcrux::jasmin::sha3::** -libcrux::**::types::index_impls::**"
interfaces = "+* -libcrux::kem::kyber::types +!libcrux_platform::**"
verify = ["make"]
clean = ["./clean.sh"]

[target.ml-kem.dependencies.fstar]
git = "https://github.com/FStarLang/fstar"
version = "v2024.01.13"
build = ["opam install . --deps-only --yes", "make -j"]

[target.ml-kem.dependencies.charon]
git = "https://github.com/AeneasVerif/charon"
rev = "89cecf5d1074fae7e8007be7f6cdf2f38e9782b1"
build = ["make -j"]

[target.ml-kem.dependencies.karamel]
git = "https://github.com/FStarLang/karamel"
rev = "08bfa78ae1df5639446e6c5897b07c9823fbf3b0"
build = ["opam install . --deps-only --yes", "make -j"]

[target.ml-kem.dependencies.eurydice]
git = "https://github.com/AeneasVerif/eurydice"
rev = "7780d2b4c44c7811d02d7e05789b5611fd497480"
build = [
    "opam install . --deps-only --yes",
    "rm -f charon",
    "ln -s ../charon/charon-ml charon",
    "rm -f krml",
    "ln -s ../karamel/lib krml",
    "make -j",
]

[target.ml-kem.dependencies.hacl-star]
git = "https://github.com/hacl-star/hacl-star"
rev = "2f5f95bc0ced5f51b3a9ecf59b870722749ec8a1"


[target.ml-kem-spec]
cargo = "--manifest-path specs/kyber/Cargo.toml"
include = "-** +compress::* +ind_cpa::* +hacspec_kyber::* +matrix::* +ntt::* +parameters::* +sampling::* +serialize::* -libcrux::hacl::sha3::** -libcrux::jasmin::sha3::** -libcrux::digest::*"
