# SLOW_MODULES += 
# ADMIT_MODULES =
# FSTAR_INCLUDE_DIRS_EXTRA += $(shell git rev-parse --show-toplevel)/fstar-helpers/fstar-bitvec \

include $(shell git rev-parse --show-toplevel)/fstar-helpers/Makefile.base
