-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_sha3]
import Aeneas
import HacspecSha3.Missing
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_sha3

/-- [hacspec_sha3::keccak_f::get]:
    Source: 'sha3/src/keccak_f.rs', lines 16:0-18:1
    Visibility: public -/
def keccak_f.get
  (state : Array Std.U64 25#usize) (x : Std.Usize) (y : Std.Usize) :
  Result Std.U64
  := do
  let i ← 5#usize * y
  let i1 ← i + x
  Array.index_usize state i1

/-- [hacspec_sha3::keccak_f::ROUND_CONSTANTS]
    Source: 'sha3/src/keccak_f.rs', lines 25:0-50:2
    Visibility: public -/
@[global_simps, irreducible]
def keccak_f.ROUND_CONSTANTS : Array Std.U64 24#usize :=
  Array.make 24#usize [
    1#u64, 32898#u64, 9223372036854808714#u64, 9223372039002292224#u64,
    32907#u64, 2147483649#u64, 9223372039002292353#u64,
    9223372036854808585#u64, 138#u64, 136#u64, 2147516425#u64, 2147483658#u64,
    2147516555#u64, 9223372036854775947#u64, 9223372036854808713#u64,
    9223372036854808579#u64, 9223372036854808578#u64, 9223372036854775936#u64,
    32778#u64, 9223372039002259466#u64, 9223372039002292353#u64,
    9223372036854808704#u64, 2147483649#u64, 9223372039002292232#u64
    ]

/-- [hacspec_sha3::keccak_f::RHO_OFFSETS]
    Source: 'sha3/src/keccak_f.rs', lines 55:0-62:2
    Visibility: public -/
@[global_simps, irreducible]
def keccak_f.RHO_OFFSETS : Array Std.U32 25#usize :=
  Array.make 25#usize [
    0#u32, 1#u32, 62#u32, 28#u32, 27#u32, 36#u32, 44#u32, 6#u32, 55#u32,
    20#u32, 3#u32, 10#u32, 43#u32, 25#u32, 39#u32, 41#u32, 45#u32, 15#u32,
    21#u32, 8#u32, 18#u32, 2#u32, 61#u32, 56#u32, 14#u32
    ]

/-- [hacspec_sha3::createi]:
    Source: 'sha3/src/lib.rs', lines 27:0-29:1 -/
def createi
  {T : Type} {F : Type} (N : Std.Usize) (coreopsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) (f : F) :
  Result (Array T N)
  := do
  core.array.from_fn N coreopsfunctionFnMutFTupleUsizeTInst f

/-- [hacspec_sha3::keccak_f::theta::closure#2]
    Source: 'sha3/src/keccak_f.rs', lines 82:12-82:41 -/
def keccak_f.theta.closure_2 := Array Std.U64 25#usize × Array Std.U64 5#usize

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#2<'_0, '_1>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 82:12-82:41 -/
def keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.theta.closure_2) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.theta.closure_2)
  := do
  let (a, a1) := c
  let i ← Array.index_usize a tupled_args
  let i1 ← tupled_args % 5#usize
  let i2 ← Array.index_usize a1 i1
  let i3 ← lift (i ^^^ i2)
  ok (i3, c)

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#2<'_0, '_1>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 82:12-82:41 -/
def keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.theta.closure_2) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c
      i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#2<'_0, '_1>}]
    Source: 'sha3/src/keccak_f.rs', lines 82:12-82:41 -/
@[reducible]
def keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.theta.closure_2 Std.Usize Std.U64 := {
  call_once :=
    keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#2<'_0, '_1>}]
    Source: 'sha3/src/keccak_f.rs', lines 82:12-82:41 -/
@[reducible]
def keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.theta.closure_2 Std.Usize Std.U64 := {
  FnOnceInst :=
    keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::theta::closure#1]
    Source: 'sha3/src/keccak_f.rs', lines 81:30-81:80 -/
@[reducible]
def keccak_f.theta.closure_1 := Array Std.U64 5#usize

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#1<'_0>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 81:30-81:80 -/
def keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.theta.closure_1) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.theta.closure_1)
  := do
  let i ← tupled_args + 4#usize
  let i1 ← i % 5#usize
  let i2 ← Array.index_usize c i1
  let i3 ← tupled_args + 1#usize
  let i4 ← i3 % 5#usize
  let i5 ← Array.index_usize c i4
  let i6 ← core.num.U64.rotate_left i5 1#u32
  let i7 ← lift (i2 ^^^ i6)
  ok (i7, c)

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#1<'_0>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 81:30-81:80 -/
def keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.theta.closure_1) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c
      i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#1<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 81:30-81:80 -/
@[reducible]
def keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.theta.closure_1 Std.Usize Std.U64 := {
  call_once :=
    keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure#1<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 81:30-81:80 -/
@[reducible]
def keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.theta.closure_1 Std.Usize Std.U64 := {
  FnOnceInst :=
    keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::theta::closure]
    Source: 'sha3/src/keccak_f.rs', lines 74:30-80:5 -/
@[reducible]
def keccak_f.theta.closure := Array Std.U64 25#usize

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure<'_0>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 74:30-80:5 -/
def keccak_f.theta.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.theta.closure) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.theta.closure)
  := do
  let i ← keccak_f.get c tupled_args 0#usize
  let i1 ← keccak_f.get c tupled_args 1#usize
  let i2 ← lift (i ^^^ i1)
  let i3 ← keccak_f.get c tupled_args 2#usize
  let i4 ← lift (i2 ^^^ i3)
  let i5 ← keccak_f.get c tupled_args 3#usize
  let i6 ← lift (i4 ^^^ i5)
  let i7 ← keccak_f.get c tupled_args 4#usize
  let i8 ← lift (i6 ^^^ i7)
  ok (i8, c)

/-- [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure<'_0>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 74:30-80:5 -/
def keccak_f.theta.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.theta.closure) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.theta.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 74:30-80:5 -/
@[reducible]
def keccak_f.theta.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.theta.closure Std.Usize Std.U64 := {
  call_once :=
    keccak_f.theta.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::theta::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::theta::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 74:30-80:5 -/
@[reducible]
def keccak_f.theta.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.theta.closure Std.Usize Std.U64 := {
  FnOnceInst := keccak_f.theta.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.theta.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::theta]:
    Source: 'sha3/src/keccak_f.rs', lines 73:0-83:1
    Visibility: public -/
def keccak_f.theta
  (state : Array Std.U64 25#usize) : Result (Array Std.U64 25#usize) := do
  let c ←
    createi 5#usize
      keccak_f.theta.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64 state
  let d ←
    createi 5#usize
      keccak_f.theta.closure_1.Insts.CoreOpsFunctionFnMutTupleUsizeU64 c
  createi 25#usize
    keccak_f.theta.closure_2.Insts.CoreOpsFunctionFnMutTupleUsizeU64 (state, d)

/-- [hacspec_sha3::keccak_f::rho::closure]
    Source: 'sha3/src/keccak_f.rs', lines 89:12-89:58 -/
@[reducible]
def keccak_f.rho.closure := Array Std.U64 25#usize

/-- [hacspec_sha3::keccak_f::rho::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::rho::closure<'_0>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 89:12-89:58 -/
def keccak_f.rho.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.rho.closure) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.rho.closure)
  := do
  let i ← Array.index_usize c tupled_args
  let i1 ← Array.index_usize keccak_f.RHO_OFFSETS tupled_args
  let i2 ← core.num.U64.rotate_left i i1
  ok (i2, c)

/-- [hacspec_sha3::keccak_f::rho::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::rho::closure<'_0>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 89:12-89:58 -/
def keccak_f.rho.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.rho.closure) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.rho.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::rho::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::rho::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 89:12-89:58 -/
@[reducible]
def keccak_f.rho.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.rho.closure Std.Usize Std.U64 := {
  call_once :=
    keccak_f.rho.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::rho::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::rho::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 89:12-89:58 -/
@[reducible]
def keccak_f.rho.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.rho.closure Std.Usize Std.U64 := {
  FnOnceInst := keccak_f.rho.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.rho.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::rho]:
    Source: 'sha3/src/keccak_f.rs', lines 88:0-90:1
    Visibility: public -/
def keccak_f.rho
  (state : Array Std.U64 25#usize) : Result (Array Std.U64 25#usize) := do
  createi 25#usize keccak_f.rho.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
    state

/-- [hacspec_sha3::keccak_f::pi::closure]
    Source: 'sha3/src/keccak_f.rs', lines 96:12-100:5 -/
@[reducible]
def keccak_f.pi.closure := Array Std.U64 25#usize

/-- [hacspec_sha3::keccak_f::pi::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::pi::closure<'_0>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 96:12-100:5 -/
def keccak_f.pi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.pi.closure) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.pi.closure)
  := do
  let y ← tupled_args / 5#usize
  let x ← tupled_args % 5#usize
  let i ← 3#usize * y
  let i1 ← x + i
  let i2 ← i1 % 5#usize
  let i3 ← keccak_f.get c i2 x
  ok (i3, c)

/-- [hacspec_sha3::keccak_f::pi::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::pi::closure<'_0>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 96:12-100:5 -/
def keccak_f.pi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.pi.closure) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.pi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::pi::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::pi::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 96:12-100:5 -/
@[reducible]
def keccak_f.pi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.pi.closure Std.Usize Std.U64 := {
  call_once :=
    keccak_f.pi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::pi::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::pi::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 96:12-100:5 -/
@[reducible]
def keccak_f.pi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.pi.closure Std.Usize Std.U64 := {
  FnOnceInst := keccak_f.pi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.pi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::pi]:
    Source: 'sha3/src/keccak_f.rs', lines 95:0-101:1
    Visibility: public -/
def keccak_f.pi
  (state : Array Std.U64 25#usize) : Result (Array Std.U64 25#usize) := do
  createi 25#usize keccak_f.pi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
    state

/-- [hacspec_sha3::keccak_f::chi::closure]
    Source: 'sha3/src/keccak_f.rs', lines 107:12-111:5 -/
@[reducible]
def keccak_f.chi.closure := Array Std.U64 25#usize

/-- [hacspec_sha3::keccak_f::chi::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::chi::closure<'_0>}::call_mut]:
    Source: 'sha3/src/keccak_f.rs', lines 107:12-111:5 -/
def keccak_f.chi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : keccak_f.chi.closure) (tupled_args : Std.Usize) :
  Result (Std.U64 × keccak_f.chi.closure)
  := do
  let y ← tupled_args / 5#usize
  let x ← tupled_args % 5#usize
  let i ← keccak_f.get c x y
  let i1 ← x + 1#usize
  let i2 ← i1 % 5#usize
  let i3 ← keccak_f.get c i2 y
  let i4 ← lift (~~~ i3)
  let i5 ← x + 2#usize
  let i6 ← i5 % 5#usize
  let i7 ← keccak_f.get c i6 y
  let i8 ← lift (i4 &&& i7)
  let i9 ← lift (i ^^^ i8)
  ok (i9, c)

/-- [hacspec_sha3::keccak_f::chi::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::chi::closure<'_0>}::call_once]:
    Source: 'sha3/src/keccak_f.rs', lines 107:12-111:5 -/
def keccak_f.chi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : keccak_f.chi.closure) (i : Std.Usize) : Result Std.U64 := do
  let (i1, _) ←
    keccak_f.chi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut c i
  ok i1

/-- Trait implementation: [hacspec_sha3::keccak_f::chi::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::keccak_f::chi::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 107:12-111:5 -/
@[reducible]
def keccak_f.chi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64 :
  core.ops.function.FnOnce keccak_f.chi.closure Std.Usize Std.U64 := {
  call_once :=
    keccak_f.chi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::keccak_f::chi::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::keccak_f::chi::closure<'_0>}]
    Source: 'sha3/src/keccak_f.rs', lines 107:12-111:5 -/
@[reducible]
def keccak_f.chi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64 :
  core.ops.function.FnMut keccak_f.chi.closure Std.Usize Std.U64 := {
  FnOnceInst := keccak_f.chi.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    keccak_f.chi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::keccak_f::chi]:
    Source: 'sha3/src/keccak_f.rs', lines 106:0-112:1
    Visibility: public -/
def keccak_f.chi
  (state : Array Std.U64 25#usize) : Result (Array Std.U64 25#usize) := do
  createi 25#usize keccak_f.chi.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
    state

/-- [hacspec_sha3::keccak_f::iota]:
    Source: 'sha3/src/keccak_f.rs', lines 118:0-121:1
    Visibility: public -/
def keccak_f.iota
  (state : Array Std.U64 25#usize) (round : Std.Usize) :
  Result (Array Std.U64 25#usize)
  := do
  let i ← Array.index_usize keccak_f.ROUND_CONSTANTS round
  let i1 ← Array.index_usize state 0#usize
  let i2 ← lift (i1 ^^^ i)
  Array.update state 0#usize i2

/-- [hacspec_sha3::keccak_f::keccak_f]: loop body 0:
    Source: 'sha3/src/keccak_f.rs', lines 131:4-133:5
    Visibility: public -/
@[rust_loop_body]
def keccak_f.keccak_f_loop.body
  (iter : core.ops.range.Range Std.Usize) (state : Array Std.U64 25#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    25#usize)) (Array Std.U64 25#usize))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done state)
  | core.option.Option.Some round =>
    let a ← keccak_f.theta state
    let a1 ← keccak_f.rho a
    let a2 ← keccak_f.pi a1
    let a3 ← keccak_f.chi a2
    let state1 ← keccak_f.iota a3 round
    ok (cont (iter1, state1))

/-- [hacspec_sha3::keccak_f::keccak_f]: loop 0:
    Source: 'sha3/src/keccak_f.rs', lines 131:4-133:5
    Visibility: public -/
@[rust_loop]
def keccak_f.keccak_f_loop
  (iter : core.ops.range.Range Std.Usize) (state : Array Std.U64 25#usize) :
  Result (Array Std.U64 25#usize)
  := do
  loop
    (fun (iter1, state1) => keccak_f.keccak_f_loop.body iter1 state1)
    (iter, state)

/-- [hacspec_sha3::keccak_f::keccak_f]:
    Source: 'sha3/src/keccak_f.rs', lines 130:0-135:1
    Visibility: public -/
@[reducible]
def keccak_f.keccak_f
  (state : Array Std.U64 25#usize) : Result (Array Std.U64 25#usize) := do
  keccak_f.keccak_f_loop { start := 0#usize, «end» := 24#usize } state

/-- [hacspec_sha3::sha3::SHA3_224_RATE]
    Source: 'sha3/src/sha3.rs', lines 5:0-5:33 -/
@[global_simps, irreducible] def sha3.SHA3_224_RATE : Std.Usize := 144#usize

/-- [hacspec_sha3::sha3::SHA3_256_RATE]
    Source: 'sha3/src/sha3.rs', lines 6:0-6:33 -/
@[global_simps, irreducible] def sha3.SHA3_256_RATE : Std.Usize := 136#usize

/-- [hacspec_sha3::sha3::SHA3_384_RATE]
    Source: 'sha3/src/sha3.rs', lines 7:0-7:33 -/
@[global_simps, irreducible] def sha3.SHA3_384_RATE : Std.Usize := 104#usize

/-- [hacspec_sha3::sha3::SHA3_512_RATE]
    Source: 'sha3/src/sha3.rs', lines 8:0-8:32 -/
@[global_simps, irreducible] def sha3.SHA3_512_RATE : Std.Usize := 72#usize

/-- [hacspec_sha3::sha3::SHAKE128_RATE]
    Source: 'sha3/src/sha3.rs', lines 9:0-9:33 -/
@[global_simps, irreducible] def sha3.SHAKE128_RATE : Std.Usize := 168#usize

/-- [hacspec_sha3::sha3::SHAKE256_RATE]
    Source: 'sha3/src/sha3.rs', lines 10:0-10:33 -/
@[global_simps, irreducible] def sha3.SHAKE256_RATE : Std.Usize := 136#usize

/-- [hacspec_sha3::sha3::SHA3_DELIM]
    Source: 'sha3/src/sha3.rs', lines 13:0-13:28 -/
@[global_simps, irreducible] def sha3.SHA3_DELIM : Std.U8 := 6#u8

/-- [hacspec_sha3::sha3::SHAKE_DELIM]
    Source: 'sha3/src/sha3.rs', lines 15:0-15:29 -/
@[global_simps, irreducible] def sha3.SHAKE_DELIM : Std.U8 := 31#u8

/-- [hacspec_sha3::sponge::squeeze::closure]
    Source: 'sha3/src/sponge.rs', lines 143:12-148:5 -/
def sponge.squeeze.closure (OUTPUT_LEN : Std.Usize) :=
  Std.Usize × Array Std.U64 25#usize

/-- [hacspec_sha3::sponge::iterate_keccak_f]:
    Source: 'sha3/src/sponge.rs', lines 120:0-126:1
    Visibility: public -/
def sponge.iterate_keccak_f
  (n : Std.Usize) (state : Array Std.U64 25#usize) :
  Result (Array Std.U64 25#usize)
  := do
  if n = 0#usize
  then ok state
  else
    let i ← n - 1#usize
    let a ← sponge.iterate_keccak_f i state
    keccak_f.keccak_f a
partial_fixpoint

/-- [hacspec_sha3::sponge::squeeze::{impl core::ops::function::FnMut<(usize,), u8> for hacspec_sha3::sponge::squeeze::closure<'_0, '_1, OUTPUT_LEN>}::call_mut]:
    Source: 'sha3/src/sponge.rs', lines 143:12-148:5 -/
def sponge.squeeze.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
  {OUTPUT_LEN : Std.Usize} (c : sponge.squeeze.closure OUTPUT_LEN)
  (tupled_args : Std.Usize) :
  Result (Std.U8 × (sponge.squeeze.closure OUTPUT_LEN))
  := do
  let (i, a) := c
  let b ← tupled_args / i
  let i1 ← b * i
  let j ← tupled_args - i1
  let state_b ← sponge.iterate_keccak_f b a
  let i2 ← j / 8#usize
  let i3 ← Array.index_usize state_b i2
  let a1 ← core.num.U64.to_le_bytes i3
  let i4 ← j % 8#usize
  let i5 ← Array.index_usize a1 i4
  ok (i5, c)

/-- [hacspec_sha3::sponge::squeeze::{impl core::ops::function::FnOnce<(usize,), u8> for hacspec_sha3::sponge::squeeze::closure<'_0, '_1, OUTPUT_LEN>}::call_once]:
    Source: 'sha3/src/sponge.rs', lines 143:12-148:5 -/
def sponge.squeeze.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
  {OUTPUT_LEN : Std.Usize} (c : sponge.squeeze.closure OUTPUT_LEN)
  (i : Std.Usize) :
  Result Std.U8
  := do
  let (i1, _) ←
    sponge.squeeze.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut c i
  ok i1

/-- Trait implementation: [hacspec_sha3::sponge::squeeze::{impl core::ops::function::FnOnce<(usize,), u8> for hacspec_sha3::sponge::squeeze::closure<'_0, '_1, OUTPUT_LEN>}]
    Source: 'sha3/src/sponge.rs', lines 143:12-148:5 -/
@[reducible]
def sponge.squeeze.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8 (OUTPUT_LEN
  : Std.Usize) : core.ops.function.FnOnce (sponge.squeeze.closure OUTPUT_LEN)
  Std.Usize Std.U8 := {
  call_once :=
    sponge.squeeze.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
}

/-- Trait implementation: [hacspec_sha3::sponge::squeeze::{impl core::ops::function::FnMut<(usize,), u8> for hacspec_sha3::sponge::squeeze::closure<'_0, '_1, OUTPUT_LEN>}]
    Source: 'sha3/src/sponge.rs', lines 143:12-148:5 -/
@[reducible]
def sponge.squeeze.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 (OUTPUT_LEN :
  Std.Usize) : core.ops.function.FnMut (sponge.squeeze.closure OUTPUT_LEN)
  Std.Usize Std.U8 := {
  FnOnceInst := sponge.squeeze.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8
    OUTPUT_LEN
  call_mut :=
    sponge.squeeze.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
}

/-- [hacspec_sha3::sponge::squeeze]:
    Source: 'sha3/src/sponge.rs', lines 142:0-149:1
    Visibility: public -/
def sponge.squeeze
  (OUTPUT_LEN : Std.Usize) (state : Array Std.U64 25#usize) (rate : Std.Usize)
  :
  Result (Array Std.U8 OUTPUT_LEN)
  := do
  createi OUTPUT_LEN
    (sponge.squeeze.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 OUTPUT_LEN)
    (rate, state)

/-- [hacspec_sha3::sponge::pad_last_block]:
    Source: 'sha3/src/sponge.rs', lines 59:0-71:1
    Visibility: public -/
def sponge.pad_last_block
  (message : Slice Std.U8) (msg_offset : Std.Usize) (remaining : Std.Usize)
  (rate : Std.Usize) (delim : Std.U8) :
  Result (Array Std.U8 200#usize)
  := do
  let buffer := Array.repeat 200#usize 0#u8
  let (s, index_mut_back) ←
    core.Array.Insts.CoreOpsIndexIndexMut.index_mut
      (core.Slice.Insts.CoreOpsIndexIndexMut
      (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) buffer { start := 0#usize, «end» := remaining }
  let i ← msg_offset + remaining
  let s1 ←
    core.Slice.Insts.CoreOpsIndexIndex.index
      (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8) message { start := msg_offset, «end» := i }
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  let buffer1 := index_mut_back s2
  let buffer2 ← Array.update buffer1 remaining delim
  let i1 ← rate - 1#usize
  let i2 ← Array.index_usize buffer2 i1
  let i3 ← lift (i2 ||| 128#u8)
  Array.update buffer2 i1 i3

/-- [hacspec_sha3::sponge::xor_block_into_state::closure]
    Source: 'sha3/src/sponge.rs', lines 18:12-26:5 -/
def sponge.xor_block_into_state.closure :=
  Std.Usize × Array Std.U64 25#usize × Slice Std.U8

/-- [hacspec_sha3::sponge::xor_block_into_state::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::sponge::xor_block_into_state::closure<'_0, '_1, '_2>}::call_mut]:
    Source: 'sha3/src/sponge.rs', lines 18:12-26:5 -/
def
  sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
  (c : sponge.xor_block_into_state.closure) (tupled_args : Std.Usize) :
  Result (Std.U64 × sponge.xor_block_into_state.closure)
  := do
  let (i, a, s) := c
  let i1 ← i / 8#usize
  if tupled_args < i1
  then
    let i2 ← Array.index_usize a tupled_args
    let i3 ← 8#usize * tupled_args
    let i4 ← i3 + 8#usize
    let s1 ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) s { start := i3, «end» := i4 }
    let r ←
      core.Array.Insts.CoreConvertTryFromShared0SliceTryFromSliceError.try_from
        8#usize core.U8.Insts.CoreMarkerCopy s1
    let a1 ←
      core.result.Result.unwrap core.array.TryFromSliceError.Insts.CoreFmtDebug
        r
    let i5 ← core.num.U64.from_le_bytes a1
    let i6 ← lift (i2 ^^^ i5)
    ok (i6, c)
  else let i2 ← Array.index_usize a tupled_args
       ok (i2, c)

/-- [hacspec_sha3::sponge::xor_block_into_state::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::sponge::xor_block_into_state::closure<'_0, '_1, '_2>}::call_once]:
    Source: 'sha3/src/sponge.rs', lines 18:12-26:5 -/
def
  sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
  (c : sponge.xor_block_into_state.closure) (i : Std.Usize) :
  Result Std.U64
  := do
  let (i1, _) ←
    sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
      c i
  ok i1

/-- Trait implementation: [hacspec_sha3::sponge::xor_block_into_state::{impl core::ops::function::FnOnce<(usize,), u64> for hacspec_sha3::sponge::xor_block_into_state::closure<'_0, '_1, '_2>}]
    Source: 'sha3/src/sponge.rs', lines 18:12-26:5 -/
@[reducible]
def
  sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  : core.ops.function.FnOnce sponge.xor_block_into_state.closure Std.Usize
  Std.U64 := {
  call_once :=
    sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64.call_once
}

/-- Trait implementation: [hacspec_sha3::sponge::xor_block_into_state::{impl core::ops::function::FnMut<(usize,), u64> for hacspec_sha3::sponge::xor_block_into_state::closure<'_0, '_1, '_2>}]
    Source: 'sha3/src/sponge.rs', lines 18:12-26:5 -/
@[reducible]
def sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
  : core.ops.function.FnMut sponge.xor_block_into_state.closure Std.Usize
  Std.U64 := {
  FnOnceInst :=
    sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU64
  call_mut :=
    sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64.call_mut
}

/-- [hacspec_sha3::sponge::xor_block_into_state]:
    Source: 'sha3/src/sponge.rs', lines 17:0-27:1
    Visibility: public -/
def sponge.xor_block_into_state
  (state : Array Std.U64 25#usize) (block : Slice Std.U8) (rate : Std.Usize) :
  Result (Array Std.U64 25#usize)
  := do
  createi 25#usize
    sponge.xor_block_into_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU64
    (rate, state, block)

/-- [hacspec_sha3::sponge::absorb_block]:
    Source: 'sha3/src/sponge.rs', lines 48:0-51:1
    Visibility: public -/
def sponge.absorb_block
  (state : Array Std.U64 25#usize) (block : Slice Std.U8) (rate : Std.Usize) :
  Result (Array Std.U64 25#usize)
  := do
  let state1 ← sponge.xor_block_into_state state block rate
  keccak_f.keccak_f state1

/-- [hacspec_sha3::sponge::absorb_final]:
    Source: 'sha3/src/sponge.rs', lines 79:0-89:1
    Visibility: public -/
def sponge.absorb_final
  (state : Array Std.U64 25#usize) (message : Slice Std.U8)
  (msg_offset : Std.Usize) (remaining : Std.Usize) (rate : Std.Usize)
  (delim : Std.U8) :
  Result (Array Std.U64 25#usize)
  := do
  let block ← sponge.pad_last_block message msg_offset remaining rate delim
  let s ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) block { start := 0#usize, «end» := rate }
  sponge.absorb_block state s rate

/-- [hacspec_sha3::sponge::absorb_rec]:
    Source: 'sha3/src/sponge.rs', lines 97:0-104:1
    Visibility: public -/
def sponge.absorb_rec
  (state : Array Std.U64 25#usize) (rate : Std.Usize) (delim : Std.U8)
  (message : Slice Std.U8) :
  Result (Array Std.U64 25#usize)
  := do
  let i ← core.slice.Slice.len message
  if i < rate
  then sponge.absorb_final state message 0#usize i rate delim
  else
    let s ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) message { start := 0#usize, «end» := rate }
    let state1 ← sponge.absorb_block state s rate
    let s1 ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) message { start := rate }
    sponge.absorb_rec state1 rate delim s1
partial_fixpoint

/-- [hacspec_sha3::sponge::absorb]:
    Source: 'sha3/src/sponge.rs', lines 114:0-116:1
    Visibility: public -/
def sponge.absorb
  (rate : Std.Usize) (delim : Std.U8) (message : Slice Std.U8) :
  Result (Array Std.U64 25#usize)
  := do
  let a := Array.repeat 25#usize 0#u64
  sponge.absorb_rec a rate delim message

/-- [hacspec_sha3::sponge::keccak]:
    Source: 'sha3/src/sponge.rs', lines 163:0-165:1
    Visibility: public -/
def sponge.keccak
  (OUTPUT_LEN : Std.Usize) (rate : Std.Usize) (delim : Std.U8)
  (message : Slice Std.U8) :
  Result (Array Std.U8 OUTPUT_LEN)
  := do
  let a ← sponge.absorb rate delim message
  sponge.squeeze OUTPUT_LEN a rate

/-- [hacspec_sha3::sha3::sha3_224]:
    Source: 'sha3/src/sha3.rs', lines 18:0-20:1
    Visibility: public -/
def sha3.sha3_224
  (message : Slice Std.U8) : Result (Array Std.U8 28#usize) := do
  sponge.keccak 28#usize sha3.SHA3_224_RATE sha3.SHA3_DELIM message

/-- [hacspec_sha3::sha3::sha3_256]:
    Source: 'sha3/src/sha3.rs', lines 23:0-25:1
    Visibility: public -/
def sha3.sha3_256
  (message : Slice Std.U8) : Result (Array Std.U8 32#usize) := do
  sponge.keccak 32#usize sha3.SHA3_256_RATE sha3.SHA3_DELIM message

/-- [hacspec_sha3::sha3::sha3_384]:
    Source: 'sha3/src/sha3.rs', lines 28:0-30:1
    Visibility: public -/
def sha3.sha3_384
  (message : Slice Std.U8) : Result (Array Std.U8 48#usize) := do
  sponge.keccak 48#usize sha3.SHA3_384_RATE sha3.SHA3_DELIM message

/-- [hacspec_sha3::sha3::sha3_512]:
    Source: 'sha3/src/sha3.rs', lines 33:0-35:1
    Visibility: public -/
def sha3.sha3_512
  (message : Slice Std.U8) : Result (Array Std.U8 64#usize) := do
  sponge.keccak 64#usize sha3.SHA3_512_RATE sha3.SHA3_DELIM message

/-- [hacspec_sha3::sha3::shake128]:
    Source: 'sha3/src/sha3.rs', lines 43:0-45:1
    Visibility: public -/
def sha3.shake128
  (N : Std.Usize) (message : Slice Std.U8) : Result (Array Std.U8 N) := do
  sponge.keccak N sha3.SHAKE128_RATE sha3.SHAKE_DELIM message

/-- [hacspec_sha3::sha3::shake256]:
    Source: 'sha3/src/sha3.rs', lines 53:0-55:1
    Visibility: public -/
def sha3.shake256
  (N : Std.Usize) (message : Slice Std.U8) : Result (Array Std.U8 N) := do
  sponge.keccak N sha3.SHAKE256_RATE sha3.SHAKE_DELIM message

/-- [hacspec_sha3::sponge::squeeze_state::closure]
    Source: 'sha3/src/sponge.rs', lines 39:35-39:72 -/
@[reducible]
def sponge.squeeze_state.closure (OUTPUT_LEN : Std.Usize) :=
  Array Std.U64 25#usize

/-- [hacspec_sha3::sponge::squeeze_state::{impl core::ops::function::FnMut<(usize,), u8> for hacspec_sha3::sponge::squeeze_state::closure<'_0, OUTPUT_LEN>}::call_mut]:
    Source: 'sha3/src/sponge.rs', lines 39:35-39:72 -/
def
  sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
  {OUTPUT_LEN : Std.Usize} (c : sponge.squeeze_state.closure OUTPUT_LEN)
  (tupled_args : Std.Usize) :
  Result (Std.U8 × (sponge.squeeze_state.closure OUTPUT_LEN))
  := do
  let i ← tupled_args / 8#usize
  let i1 ← Array.index_usize c i
  let a ← core.num.U64.to_le_bytes i1
  let i2 ← tupled_args % 8#usize
  let i3 ← Array.index_usize a i2
  ok (i3, c)

/-- [hacspec_sha3::sponge::squeeze_state::{impl core::ops::function::FnOnce<(usize,), u8> for hacspec_sha3::sponge::squeeze_state::closure<'_0, OUTPUT_LEN>}::call_once]:
    Source: 'sha3/src/sponge.rs', lines 39:35-39:72 -/
def
  sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
  {OUTPUT_LEN : Std.Usize} (c : sponge.squeeze_state.closure OUTPUT_LEN)
  (i : Std.Usize) :
  Result Std.U8
  := do
  let (i1, _) ←
    sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
      c i
  ok i1

/-- Trait implementation: [hacspec_sha3::sponge::squeeze_state::{impl core::ops::function::FnOnce<(usize,), u8> for hacspec_sha3::sponge::squeeze_state::closure<'_0, OUTPUT_LEN>}]
    Source: 'sha3/src/sponge.rs', lines 39:35-39:72 -/
@[reducible]
def sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8
  (OUTPUT_LEN : Std.Usize) : core.ops.function.FnOnce
  (sponge.squeeze_state.closure OUTPUT_LEN) Std.Usize Std.U8 := {
  call_once :=
    sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8.call_once
}

/-- Trait implementation: [hacspec_sha3::sponge::squeeze_state::{impl core::ops::function::FnMut<(usize,), u8> for hacspec_sha3::sponge::squeeze_state::closure<'_0, OUTPUT_LEN>}]
    Source: 'sha3/src/sponge.rs', lines 39:35-39:72 -/
@[reducible]
def sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8
  (OUTPUT_LEN : Std.Usize) : core.ops.function.FnMut
  (sponge.squeeze_state.closure OUTPUT_LEN) Std.Usize Std.U8 := {
  FnOnceInst :=
    sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeU8
    OUTPUT_LEN
  call_mut :=
    sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
}

/-- [hacspec_sha3::sponge::squeeze_state]:
    Source: 'sha3/src/sponge.rs', lines 33:0-42:1
    Visibility: public -/
def sponge.squeeze_state
  {OUTPUT_LEN : Std.Usize} (state : Array Std.U64 25#usize)
  (output : Array Std.U8 OUTPUT_LEN) (out_offset : Std.Usize) (len : Std.Usize)
  :
  Result (Array Std.U8 OUTPUT_LEN)
  := do
  let bytes ←
    createi 200#usize
      (sponge.squeeze_state.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8
      OUTPUT_LEN) state
  let i ← out_offset + len
  let (s, index_mut_back) ←
    core.Array.Insts.CoreOpsIndexIndexMut.index_mut
      (core.Slice.Insts.CoreOpsIndexIndexMut
      (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) output { start := out_offset, «end» := i }
  let s1 ←
    core.Array.Insts.CoreOpsIndexIndex.index
      (core.Slice.Insts.CoreOpsIndexIndex
      (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
      Std.U8)) bytes { start := 0#usize, «end» := len }
  let s2 ← core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s s1
  ok (index_mut_back s2)

end hacspec_sha3
