/* automatically generated by rust-bindgen 0.59.2 */

pub const JADE_HASH_SHA256_AMD64_REF_BYTES: u32 = 32;
pub const JADE_HASH_SHA256_AMD64_REF_ALGNAME: &[u8; 7usize] = b"SHA256\0";
pub const JADE_SCALARMULT_CURVE25519_AMD64_REF5_BYTES: u32 = 32;
pub const JADE_SCALARMULT_CURVE25519_AMD64_REF5_SCALARBYTES: u32 = 32;
pub const JADE_SCALARMULT_CURVE25519_AMD64_REF5_ALGNAME: &[u8; 11usize] = b"Curve25519\0";
pub const JADE_SCALARMULT_CURVE25519_AMD64_MULX_BYTES: u32 = 32;
pub const JADE_SCALARMULT_CURVE25519_AMD64_MULX_SCALARBYTES: u32 = 32;
pub const JADE_SCALARMULT_CURVE25519_AMD64_MULX_ALGNAME: &[u8; 11usize] = b"Curve25519\0";
extern "C" {
    pub fn jade_hash_sha256_amd64_ref(
        out: *mut u8,
        in_: *mut u8,
        length: u64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn jade_scalarmult_curve25519_amd64_ref5(
        r: *mut u8,
        k: *mut u8,
        u: *mut u8,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn jade_scalarmult_curve25519_amd64_ref5_base(
        r: *mut u8,
        k: *mut u8,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn jade_scalarmult_curve25519_amd64_mulx(
        r: *mut u8,
        k: *mut u8,
        u: *mut u8,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn jade_scalarmult_curve25519_amd64_mulx_base(
        r: *mut u8,
        k: *mut u8,
    ) -> ::std::os::raw::c_int;
}
