-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_ml_kem]: proof obligations
import Aeneas
import CoreModels
import HacspecMlKem.Extraction.Types
import HacspecMlKem.Extraction.Funs
import HacspecMlKem.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_ml_kem

@[spec]
theorem parameters.cpa_ciphertext_size.spec.proof (rank : Std.Usize) :
  parameters.cpa_ciphertext_size.spec rank
  := by sorry

@[spec]
theorem parameters.rank_to_params.spec.proof (rank : Std.Usize) :
  parameters.rank_to_params.spec rank
  := by sorry

@[spec]
theorem parameters.t_as_ntt_encoded_size.spec.proof (rank : Std.Usize) :
  parameters.t_as_ntt_encoded_size.spec rank
  := by sorry

@[spec]
theorem parameters.ranked_bytes_per_ring_element.spec.proof (rank : Std.Usize)
  : parameters.ranked_bytes_per_ring_element.spec rank
  := by sorry

@[spec]
theorem parameters.cpa_public_key_size.spec.proof (rank : Std.Usize) :
  parameters.cpa_public_key_size.spec rank
  := by sorry

@[spec]
theorem parameters.cpa_private_key_size.spec.proof (rank : Std.Usize) :
  parameters.cpa_private_key_size.spec rank
  := by sorry

@[spec]
theorem parameters.cca_private_key_size.spec.proof (rank : Std.Usize) :
  parameters.cca_private_key_size.spec rank
  := by sorry

@[spec]
theorem parameters.vector_u_compression_factor.spec.proof (rank : Std.Usize) :
  parameters.vector_u_compression_factor.spec rank
  := by sorry

@[spec]
theorem parameters.vector_v_compression_factor.spec.proof (rank : Std.Usize) :
  parameters.vector_v_compression_factor.spec rank
  := by sorry

@[spec]
theorem parameters.c1_block_size.spec.proof (rank : Std.Usize) :
  parameters.c1_block_size.spec rank
  := by sorry

@[spec]
theorem parameters.c1_size.spec.proof (rank : Std.Usize) :
  parameters.c1_size.spec rank
  := by sorry

@[spec]
theorem parameters.c2_size.spec.proof (rank : Std.Usize) :
  parameters.c2_size.spec rank
  := by sorry

@[spec]
theorem parameters.eta1.spec.proof (rank : Std.Usize) :
  parameters.eta1.spec rank
  := by sorry

@[spec]
theorem parameters.eta2.spec.proof (rank : Std.Usize) :
  parameters.eta2.spec rank
  := by sorry

@[spec]
theorem parameters.eta1_randomness_size.spec.proof (rank : Std.Usize) :
  parameters.eta1_randomness_size.spec rank
  := by sorry

@[spec]
theorem parameters.eta2_randomness_size.spec.proof (rank : Std.Usize) :
  parameters.eta2_randomness_size.spec rank
  := by sorry

@[spec]
theorem parameters.implicit_rejection_hash_input_size.spec.proof
  (rank : Std.Usize) : parameters.implicit_rejection_hash_input_size.spec rank
  := by sorry

@[spec]
theorem compress.compress.spec.proof
  (re : Array parameters.FieldElement 256#usize)
  (bits_per_compressed_coefficient : Std.Usize) :
  compress.compress.spec re bits_per_compressed_coefficient
  := by sorry

@[spec]
theorem compress.decompress.spec.proof
  (re : Array parameters.FieldElement 256#usize)
  (bits_per_compressed_coefficient : Std.Usize) :
  compress.decompress.spec re bits_per_compressed_coefficient
  := by sorry

@[spec]
theorem compress.compress_d.spec.proof (fe : parameters.FieldElement)
  (to_bit_size : Std.Usize) : compress.compress_d.spec fe to_bit_size
  := by sorry

@[spec]
theorem compress.decompress_d.spec.proof (fe : parameters.FieldElement)
  (to_bit_size : Std.Usize) : compress.decompress_d.spec fe to_bit_size
  := by sorry

@[spec]
theorem
  ind_cca.keygen_internal.spec.proof (RANK : Std.Usize) (EK_SIZE : Std.Usize)
                                    (DK_PKE_SIZE : Std.Usize) (DK_SIZE :
                                    Std.Usize)
  (params : parameters.MlKemParams) (d : Array Std.U8 32#usize)
  (z : Array Std.U8 32#usize) :
  ind_cca.keygen_internal.spec RANK EK_SIZE DK_PKE_SIZE DK_SIZE params d z
  := by sorry

@[spec]
theorem
  ind_cca.encaps_internal.spec.proof (RANK : Std.Usize) (U_SIZE : Std.Usize)
                                    (V_SIZE : Std.Usize) (CT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (ek : Slice Std.U8)
  (m : Array Std.U8 32#usize) :
  ind_cca.encaps_internal.spec RANK U_SIZE V_SIZE CT_SIZE params ek m
  := by sorry

@[spec]
theorem
  ind_cca.decaps_internal.spec.proof (RANK : Std.Usize) (EK_SIZE : Std.Usize)
                                    {DK_SIZE : Std.Usize} (DK_PKE_SIZE :
                                    Std.Usize) (U_SIZE : Std.Usize) (V_SIZE :
                                    Std.Usize) {CT_SIZE : Std.Usize}
                                    (J_INPUT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (dk : Array Std.U8 DK_SIZE)
  (c : Array Std.U8 CT_SIZE) :
  ind_cca.decaps_internal.spec RANK EK_SIZE DK_PKE_SIZE U_SIZE V_SIZE
  J_INPUT_SIZE params dk c
  := by sorry

@[spec]
theorem
  ind_cca.generate_keypair.spec.proof (RANK : Std.Usize) (EK_SIZE : Std.Usize)
                                     (DK_SIZE : Std.Usize) (DK_PKE_SIZE :
                                     Std.Usize)
  (params : parameters.MlKemParams) (randomness : Array Std.U8 64#usize) :
  ind_cca.generate_keypair.spec RANK EK_SIZE DK_SIZE DK_PKE_SIZE params
  randomness
  := by sorry

@[spec]
theorem ind_cca.public_key_modulus_check.spec.proof {EK_SIZE : Std.Usize}
  (params : parameters.MlKemParams) (ek : Array Std.U8 EK_SIZE) :
  ind_cca.public_key_modulus_check.spec params ek
  := by sorry

@[spec]
theorem
  ind_cca.encapsulate.spec.proof (RANK : Std.Usize) {EK_SIZE : Std.Usize}
                                (U_SIZE : Std.Usize) (V_SIZE : Std.Usize)
                                (CT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (ek : Array Std.U8 EK_SIZE)
  (m : Array Std.U8 32#usize) :
  ind_cca.encapsulate.spec RANK U_SIZE V_SIZE CT_SIZE params ek m
  := by sorry

@[spec]
theorem
  ind_cca.decapsulate.spec.proof (RANK : Std.Usize) (EK_SIZE : Std.Usize)
                                {DK_SIZE : Std.Usize} (DK_PKE_SIZE : Std.Usize)
                                (U_SIZE : Std.Usize) (V_SIZE : Std.Usize)
                                {CT_SIZE : Std.Usize} (J_INPUT_SIZE :
                                Std.Usize) (params : parameters.MlKemParams)
  (dk : Array Std.U8 DK_SIZE) (c : Array Std.U8 CT_SIZE) :
  ind_cca.decapsulate.spec RANK EK_SIZE DK_PKE_SIZE U_SIZE V_SIZE J_INPUT_SIZE
  params dk c
  := by sorry

@[spec]
theorem
  ind_cca.ind_cca_unpack_generate_keypair.spec.proof (RANK : Std.Usize)
                                                    (EK_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (randomness : Array Std.U8 64#usize) :
  ind_cca.ind_cca_unpack_generate_keypair.spec RANK EK_SIZE params randomness
  := by sorry

@[spec]
theorem
  ind_cca.ind_cca_unpack_encapsulate.spec.proof {RANK : Std.Usize} (U_SIZE :
                                               Std.Usize) (V_SIZE : Std.Usize)
                                               (CT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (public_key_hash : Array Std.U8 32#usize)
  (t_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (m_A : Array (Array (Array parameters.FieldElement 256#usize) RANK) RANK)
  (randomness : Array Std.U8 32#usize) :
  ind_cca.ind_cca_unpack_encapsulate.spec U_SIZE V_SIZE CT_SIZE params
  public_key_hash t_as_ntt m_A randomness
  := by sorry

@[spec]
theorem
  ind_cca.ind_cca_unpack_decapsulate.spec.proof {RANK : Std.Usize} (U_SIZE :
                                               Std.Usize) (V_SIZE : Std.Usize)
                                               {CT_SIZE : Std.Usize}
                                               (J_INPUT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (public_key_hash : Array Std.U8 32#usize)
  (implicit_rejection_value : Array Std.U8 32#usize)
  (ciphertext : Array Std.U8 CT_SIZE)
  (secret_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (t_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (m_A : Array (Array (Array parameters.FieldElement 256#usize) RANK) RANK) :
  ind_cca.ind_cca_unpack_decapsulate.spec U_SIZE V_SIZE J_INPUT_SIZE params
  public_key_hash implicit_rejection_value ciphertext secret_as_ntt t_as_ntt
  m_A
  := by sorry

@[spec]
theorem ind_cpa.sample_secret.spec.proof (eta : Std.Usize)
  (prf_input : Array Std.U8 33#usize) :
  ind_cpa.sample_secret.spec eta prf_input
  := by sorry

@[spec]
theorem ind_cpa.concat_byte.spec.proof {N : Std.Usize} (N1 : Std.Usize)
  (a : Array Std.U8 N) (b : Std.U8) : ind_cpa.concat_byte.spec N1 a b
  := by sorry

@[spec]
theorem ind_cpa.sample_vector_cbd.spec.proof (RANK : Std.Usize)
  (eta : Std.Usize) (seed : Slice Std.U8) (domain_separator : Std.U8) :
  ind_cpa.sample_vector_cbd.spec RANK eta seed domain_separator
  := by sorry

@[spec]
theorem ind_cpa.sample_vector_cbd_then_ntt.spec.proof (RANK : Std.Usize)
  (eta : Std.Usize) (seed : Slice Std.U8) (domain_separator : Std.U8) :
  ind_cpa.sample_vector_cbd_then_ntt.spec RANK eta seed domain_separator
  := by sorry

@[spec]
theorem ind_cpa.generate_keypair_unpacked.spec.proof (RANK : Std.Usize)
  (params : parameters.MlKemParams) (key_generation_seed : Slice Std.U8) :
  ind_cpa.generate_keypair_unpacked.spec RANK params key_generation_seed
  := by sorry

@[spec]
theorem
  ind_cpa.generate_keypair.spec.proof (RANK : Std.Usize) (EK_SIZE : Std.Usize)
                                     (DK_PKE_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (key_generation_seed : Slice Std.U8) :
  ind_cpa.generate_keypair.spec RANK EK_SIZE DK_PKE_SIZE params
  key_generation_seed
  := by sorry

@[spec]
theorem
  ind_cpa.encrypt.spec.proof (RANK : Std.Usize) (U_SIZE : Std.Usize) (V_SIZE :
                            Std.Usize) (CT_SIZE : Std.Usize)
  (params : parameters.MlKemParams) (ek : Slice Std.U8)
  (message : Array Std.U8 32#usize) (randomness : Slice Std.U8) :
  ind_cpa.encrypt.spec RANK U_SIZE V_SIZE CT_SIZE params ek message randomness
  := by sorry

@[spec]
theorem
  ind_cpa.encrypt_unpacked.spec.proof {RANK : Std.Usize} (U_SIZE : Std.Usize)
                                     (V_SIZE : Std.Usize) (CT_SIZE : Std.Usize)
  (params : parameters.MlKemParams)
  (t_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (A_as_ntt : Array (Array (Array parameters.FieldElement 256#usize) RANK)
  RANK) (message : Array Std.U8 32#usize) (randomness : Slice Std.U8) :
  ind_cpa.encrypt_unpacked.spec U_SIZE V_SIZE CT_SIZE params t_as_ntt A_as_ntt
  message randomness
  := by sorry

@[spec]
theorem ind_cpa.decrypt.spec.proof (RANK : Std.Usize)
  (params : parameters.MlKemParams) (dk : Slice Std.U8)
  (ciphertext : Slice Std.U8) : ind_cpa.decrypt.spec RANK params dk ciphertext
  := by sorry

@[spec]
theorem ind_cpa.decrypt_unpacked.spec.proof {RANK : Std.Usize}
  (params : parameters.MlKemParams)
  (secret_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (ciphertext : Slice Std.U8) :
  ind_cpa.decrypt_unpacked.spec params secret_as_ntt ciphertext
  := by sorry

@[spec]
theorem invert_ntt.ntt_inverse_layer_n.spec.proof {N : Std.Usize}
  (p : Array parameters.FieldElement N) (len : Std.Usize)
  (zetas : Slice parameters.FieldElement) :
  invert_ntt.ntt_inverse_layer_n.spec p len zetas
  := by sorry

@[spec]
theorem invert_ntt.ntt_inverse_layer.spec.proof
  (p : Array parameters.FieldElement 256#usize) (layer : Std.Usize) :
  invert_ntt.ntt_inverse_layer.spec p layer
  := by sorry

@[spec]
theorem matrix.sample_matrix_A.spec.proof (RANK : Std.Usize)
  (seed_for_A : Slice Std.U8) (transpose : Bool) :
  matrix.sample_matrix_A.spec RANK seed_for_A transpose
  := by sorry

@[spec]
theorem ntt.get_zeta.spec.proof (i : Std.Usize) : ntt.get_zeta.spec i
  := by sorry

@[spec]
theorem ntt.ntt_layer_n.spec.proof {N : Std.Usize}
  (p : Array parameters.FieldElement N) (len : Std.Usize)
  (zetas : Slice parameters.FieldElement) : ntt.ntt_layer_n.spec p len zetas
  := by sorry

@[spec]
theorem ntt.ntt_layer.spec.proof (p : Array parameters.FieldElement 256#usize)
  (layer : Std.Usize) : ntt.ntt_layer.spec p layer
  := by sorry

@[spec]
theorem ntt.ntt_multiply_n.spec.proof {N : Std.Usize}
  (p1 : Array parameters.FieldElement N) (p2 : Array parameters.FieldElement N)
  (zetas : Slice parameters.FieldElement) : ntt.ntt_multiply_n.spec p1 p2 zetas
  := by sorry

@[spec]
theorem
  sampling.sample_ntt.spec.proof (N : Std.Usize) (N8 : Std.Usize) {N12 :
                                Std.Usize} (N96 : Std.Usize)
  (bytes : Array Std.U8 N12) : sampling.sample_ntt.spec N N8 N96 bytes
  := by sorry

@[spec]
theorem sampling.sum_coins.spec.proof (eta : Std.Usize) (coins : Slice Bool) :
  sampling.sum_coins.spec eta coins
  := by sorry

@[spec]
theorem
  sampling.sample_poly_cbd.spec.proof {ETA64 : Std.Usize} (ETA512 : Std.Usize)
  (eta : Std.Usize) (bytes : Array Std.U8 ETA64) :
  sampling.sample_poly_cbd.spec ETA512 eta bytes
  := by sorry

@[spec]
theorem serialize.bytes_to_bits.spec.proof {N : Std.Usize} (N8 : Std.Usize)
  (bytes : Array Std.U8 N) : serialize.bytes_to_bits.spec N8 bytes
  := by sorry

@[spec]
theorem serialize.bits_to_bytes.spec.proof (N : Std.Usize) {N8 : Std.Usize}
  (bv : Array Bool N8) : serialize.bits_to_bytes.spec N bv
  := by sorry

@[spec]
theorem
  serialize.bitvector_from_bounded_ints.spec.proof {N : Std.Usize} (Nd :
                                                  Std.Usize)
  (input : Array Std.U16 N) (d : Std.Usize) :
  serialize.bitvector_from_bounded_ints.spec Nd input d
  := by sorry

@[spec]
theorem serialize.byte_encode.spec.proof (D32 : Std.Usize) (D256 : Std.Usize)
  (p : Array parameters.FieldElement 256#usize) (d : Std.Usize) :
  serialize.byte_encode.spec D32 D256 p d
  := by sorry

@[spec]
theorem
  serialize.bitvector_to_bounded_ints.spec.proof (N : Std.Usize) {Nd :
                                                Std.Usize}
  (input : Array Bool Nd) (d : Std.Usize) :
  serialize.bitvector_to_bounded_ints.spec N input d
  := by sorry

@[spec]
theorem
  serialize.byte_decode_generic.spec.proof (N : Std.Usize) (N8 : Std.Usize) {Nd
                                          : Std.Usize} (Nd8 : Std.Usize)
  (b : Array Std.U8 Nd) (d : Std.Usize) :
  serialize.byte_decode_generic.spec N N8 Nd8 b d
  := by sorry

@[spec]
theorem serialize.byte_decode.spec.proof {D32 : Std.Usize} (D256 : Std.Usize)
  (b : Array Std.U8 D32) (d : Std.Usize) : serialize.byte_decode.spec D256 b d
  := by sorry

@[spec]
theorem serialize.serialize_secret_key_into.spec.proof {RANK : Std.Usize}
  (vector : Array (Array parameters.FieldElement 256#usize) RANK)
  (out : Slice Std.U8) : serialize.serialize_secret_key_into.spec vector out
  := by sorry

@[spec]
theorem serialize.vector_decode_12.spec.proof (RANK : Std.Usize)
  (encoded : Slice Std.U8) : serialize.vector_decode_12.spec RANK encoded
  := by sorry

@[spec]
theorem serialize.byte_encode_into.spec.proof
  (p : Array parameters.FieldElement 256#usize) (d : Std.Usize)
  (out : Slice Std.U8) : serialize.byte_encode_into.spec p d out
  := by sorry

@[spec]
theorem serialize.byte_decode_dyn.spec.proof (b : Slice Std.U8) (d : Std.Usize)
  : serialize.byte_decode_dyn.spec b d
  := by sorry

@[spec]
theorem serialize.compress_then_serialize_u_into.spec.proof {RANK : Std.Usize}
  (u : Array (Array parameters.FieldElement 256#usize) RANK) (du : Std.Usize)
  (out : Slice Std.U8) : serialize.compress_then_serialize_u_into.spec u du out
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_u.spec.proof {RANK : Std.Usize} (U_SIZE :
                                                Std.Usize)
  (u : Array (Array parameters.FieldElement 256#usize) RANK) (du : Std.Usize) :
  serialize.compress_then_serialize_u.spec U_SIZE u du
  := by sorry

@[spec]
theorem serialize.compress_then_serialize_v.spec.proof (V_SIZE : Std.Usize)
  (v : Array parameters.FieldElement 256#usize) (dv : Std.Usize) :
  serialize.compress_then_serialize_v.spec V_SIZE v dv
  := by sorry

@[spec]
theorem serialize.deserialize_then_decompress_u.spec.proof (RANK : Std.Usize)
  (ciphertext : Slice Std.U8) (du : Std.Usize) :
  serialize.deserialize_then_decompress_u.spec RANK ciphertext du
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_u_then_ntt.spec.proof (RANK :
                                                             Std.Usize)
  (ciphertext : Slice Std.U8) (du : Std.Usize) :
  serialize.deserialize_then_decompress_u_then_ntt.spec RANK ciphertext du
  := by sorry

@[spec]
theorem serialize.deserialize_then_decompress_v.spec.proof
  (serialized : Slice Std.U8) (dv : Std.Usize) :
  serialize.deserialize_then_decompress_v.spec serialized dv
  := by sorry

@[spec]
theorem
  serialize.deserialize_ring_elements_reduced.spec.proof (RANK : Std.Usize)
  (encoded : Slice Std.U8) :
  serialize.deserialize_ring_elements_reduced.spec RANK encoded
  := by sorry

@[spec]
theorem
  serialize.serialize_secret_key.spec.proof {RANK : Std.Usize} (T_SIZE :
                                           Std.Usize)
  (vector : Array (Array parameters.FieldElement 256#usize) RANK) :
  serialize.serialize_secret_key.spec T_SIZE vector
  := by sorry

@[spec]
theorem
  serialize.serialize_public_key.spec.proof {RANK : Std.Usize} (EK_SIZE :
                                           Std.Usize)
  (t_as_ntt : Array (Array parameters.FieldElement 256#usize) RANK)
  (seed_for_A : Slice Std.U8) :
  serialize.serialize_public_key.spec EK_SIZE t_as_ntt seed_for_A
  := by sorry

@[spec]
theorem parameters.FieldElement.new.spec.proof (val : Std.U16) :
  parameters.FieldElement.new.spec val
  := by sorry

end hacspec_ml_kem
