# This is a libcrux-specific makefile for F*, that uses the more
# generic makefile `Makefile.generic.template`

FSTAR_INCLUDE_DIRS_EXTRA = $(shell git rev-parse --show-toplevel)/libcrux-ml-kem/proofs/fstar/spec $(HACL_HOME)/specs
include $(shell git rev-parse --show-toplevel)/fstar-helpers/Makefile.generic.template
