[package]
name = "libcrux-polynomials-aarch64"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libcrux-polynomials = { path = "../polynomials" }
libcrux-sha3 = { path = "../libcrux-sha3" }
