files:
  - name: libcrux_digest
    api:
      - [ libcrux, digest ]
  - name: libcrux_platform
    api:
      - [ libcrux_platform ]
  - name: libcrux_kyber
    api:
      - [ libcrux_kyber, kyber768 ]
    private:
      - [ libcrux_kyber, "*" ]
  - name: core
    private:
      - [ core, "*" ]
