# Verify the four root spec modules.
ROOTS = Hacspec_sha3.fst \
        Hacspec_sha3.Keccak_f.fst \
        Hacspec_sha3.Sha3.fst \
        Hacspec_sha3.Sponge.fst

include $(shell git rev-parse --show-toplevel)/fstar-helpers/Makefile.base
