-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_ml_dsa]: proof obligations
import Aeneas
import CoreModels
import HacspecMlDsa.Extraction.Types
import HacspecMlDsa.Extraction.Funs
import HacspecMlDsa.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_ml_dsa

@[spec]
theorem arithmetic.mod_pm.spec.proof (a : Std.I32) (m : Std.I32) :
  arithmetic.mod_pm.spec a m
  := by sorry

@[spec]
theorem arithmetic.power2round.spec.proof (r : Std.I32) :
  arithmetic.power2round.spec r
  := by sorry

@[spec]
theorem arithmetic.decompose.spec.proof (r : Std.I32) (gamma2 : Std.I32) :
  arithmetic.decompose.spec r gamma2
  := by sorry

@[spec]
theorem arithmetic.high_bits.spec.proof (r : Std.I32) (gamma2 : Std.I32) :
  arithmetic.high_bits.spec r gamma2
  := by sorry

@[spec]
theorem arithmetic.low_bits.spec.proof (r : Std.I32) (gamma2 : Std.I32) :
  arithmetic.low_bits.spec r gamma2
  := by sorry

@[spec]
theorem arithmetic.make_hint.spec.proof (z : Std.I32) (r : Std.I32)
  (gamma2 : Std.I32) : arithmetic.make_hint.spec z r gamma2
  := by sorry

@[spec]
theorem arithmetic.use_hint.spec.proof (hint : Bool) (r : Std.I32)
  (gamma2 : Std.I32) : arithmetic.use_hint.spec hint r gamma2
  := by sorry

@[spec]
theorem encoding.simple_bit_pack.spec.proof (BYTES : Std.Usize)
  (w : Array Std.I32 256#usize) (b : Std.Usize) :
  encoding.simple_bit_pack.spec BYTES w b
  := by sorry

@[spec]
theorem encoding.bit_pack.spec.proof (BYTES : Std.Usize)
  (w : Array Std.I32 256#usize) (a : Std.Usize) (b : Std.Usize) :
  encoding.bit_pack.spec BYTES w a b
  := by sorry

@[spec]
theorem encoding.bit_unpack.spec.proof (v : Slice Std.U8) (a : Std.Usize)
  (b : Std.Usize) : encoding.bit_unpack.spec v a b
  := by sorry

@[spec]
theorem
  encoding.hint_bit_pack.spec.proof {K : Std.Usize} (HINT_BYTES : Std.Usize)
  (h : Array (Array Bool 256#usize) K) (omega : Std.Usize) :
  encoding.hint_bit_pack.spec HINT_BYTES h omega
  := by sorry

@[spec]
theorem encoding.hint_bit_unpack.spec.proof (K : Std.Usize) (y : Slice Std.U8)
  (omega : Std.Usize) : encoding.hint_bit_unpack.spec K y omega
  := by sorry

@[spec]
theorem encoding.pk_encode.spec.proof {K : Std.Usize} (PK_SIZE : Std.Usize)
  (rho : Array Std.U8 32#usize) (t1 : Array (Array Std.I32 256#usize) K) :
  encoding.pk_encode.spec PK_SIZE rho t1
  := by sorry

@[spec]
theorem encoding.pk_decode.spec.proof (K : Std.Usize) (pk : Slice Std.U8) :
  encoding.pk_decode.spec K pk
  := by sorry

@[spec]
theorem
  encoding.sk_encode.spec.proof {K : Std.Usize} {L : Std.Usize} (SK_SIZE :
                               Std.Usize) (rho : Array Std.U8 32#usize)
  (key : Array Std.U8 32#usize) (tr : Array Std.U8 64#usize)
  (s1 : Array (Array Std.I32 256#usize) L)
  (s2 : Array (Array Std.I32 256#usize) K)
  (t0 : Array (Array Std.I32 256#usize) K) (params : parameters.MlDsaParams) :
  encoding.sk_encode.spec SK_SIZE rho key tr s1 s2 t0 params
  := by sorry

@[spec]
theorem encoding.sk_decode.spec.proof (K : Std.Usize) (L : Std.Usize)
  (sk : Slice Std.U8) (params : parameters.MlDsaParams) :
  encoding.sk_decode.spec K L sk params
  := by sorry

@[spec]
theorem
  encoding.sig_encode.spec.proof {K : Std.Usize} {L : Std.Usize} (SIG_SIZE :
                                Std.Usize) (c_tilde : Slice Std.U8)
  (z : Array (Array Std.I32 256#usize) L) (h : Array (Array Bool 256#usize) K)
  (params : parameters.MlDsaParams) :
  encoding.sig_encode.spec SIG_SIZE c_tilde z h params
  := by sorry

@[spec]
theorem
  encoding.sig_decode.spec.proof (K : Std.Usize) (L : Std.Usize) (C_TILDE_LEN :
                                Std.Usize) (sigma : Slice Std.U8)
  (params : parameters.MlDsaParams) :
  encoding.sig_decode.spec K L C_TILDE_LEN sigma params
  := by sorry

@[spec]
theorem encoding.w1_encode.spec.proof {K : Std.Usize} (W1_BYTES : Std.Usize)
  (w1 : Array (Array Std.I32 256#usize) K) (params : parameters.MlDsaParams) :
  encoding.w1_encode.spec W1_BYTES w1 params
  := by sorry

@[spec]
theorem
  ml_dsa.keygen_internal.spec.proof (K : Std.Usize) (L : Std.Usize) (PK_SIZE :
                                   Std.Usize) (SK_SIZE : Std.Usize)
  (xi : Array Std.U8 32#usize) (params : parameters.MlDsaParams) :
  ml_dsa.keygen_internal.spec K L PK_SIZE SK_SIZE xi params
  := by sorry

@[spec]
theorem
  ml_dsa.try_sign_iteration.spec.proof {K : Std.Usize} {L : Std.Usize}
                                      (SIG_SIZE : Std.Usize) (W1_BYTES :
                                      Std.Usize) (C_TILDE_LEN : Std.Usize)
  (a_hat : Array (Array (Array Std.I32 256#usize) L) K)
  (s1_hat : Array (Array Std.I32 256#usize) L)
  (s2_hat : Array (Array Std.I32 256#usize) K)
  (t0_hat : Array (Array Std.I32 256#usize) K) (mu : Array Std.U8 64#usize)
  (rho_pp : Array Std.U8 64#usize) (kappa : Std.Usize)
  (params : parameters.MlDsaParams) :
  ml_dsa.try_sign_iteration.spec SIG_SIZE W1_BYTES C_TILDE_LEN a_hat s1_hat
  s2_hat t0_hat mu rho_pp kappa params
  := by sorry

@[spec]
theorem
  ml_dsa.sign_internal.spec.proof (K : Std.Usize) (L : Std.Usize) (SIG_SIZE :
                                 Std.Usize) (W1_BYTES : Std.Usize) (C_TILDE_LEN
                                 : Std.Usize) (sk : Slice Std.U8)
  (m_prime : Slice Std.U8) (rnd : Array Std.U8 32#usize)
  (params : parameters.MlDsaParams) :
  ml_dsa.sign_internal.spec K L SIG_SIZE W1_BYTES C_TILDE_LEN sk m_prime rnd
  params
  := by sorry

@[spec]
theorem
  ml_dsa.verify_internal.spec.proof (K : Std.Usize) (L : Std.Usize)
                                   (C_TILDE_LEN : Std.Usize) (W1_BYTES :
                                   Std.Usize) (pk : Slice Std.U8)
  (m_prime : Slice Std.U8) (sigma : Slice Std.U8)
  (params : parameters.MlDsaParams) :
  ml_dsa.verify_internal.spec K L C_TILDE_LEN W1_BYTES pk m_prime sigma params
  := by sorry

@[spec]
theorem ml_dsa.format_m_prime.spec.proof (message : Slice Std.U8)
  (ctx : Slice Std.U8) : ml_dsa.format_m_prime.spec message ctx
  := by sorry

@[spec]
theorem
  ml_dsa.keygen.spec.proof (K : Std.Usize) (L : Std.Usize) (PK_SIZE :
                          Std.Usize) (SK_SIZE : Std.Usize)
  (xi : Array Std.U8 32#usize) (params : parameters.MlDsaParams) :
  ml_dsa.keygen.spec K L PK_SIZE SK_SIZE xi params
  := by sorry

@[spec]
theorem
  ml_dsa.sign.spec.proof (K : Std.Usize) (L : Std.Usize) (SIG_SIZE : Std.Usize)
                        (W1_BYTES : Std.Usize) (C_TILDE_LEN : Std.Usize)
  (sk : Slice Std.U8) (message : Slice Std.U8) (ctx : Slice Std.U8)
  (rnd : Array Std.U8 32#usize) (params : parameters.MlDsaParams) :
  ml_dsa.sign.spec K L SIG_SIZE W1_BYTES C_TILDE_LEN sk message ctx rnd params
  := by sorry

@[spec]
theorem
  ml_dsa.verify.spec.proof (K : Std.Usize) (L : Std.Usize) (C_TILDE_LEN :
                          Std.Usize) (W1_BYTES : Std.Usize) (pk : Slice Std.U8)
  (message : Slice Std.U8) (sigma : Slice Std.U8) (ctx : Slice Std.U8)
  (params : parameters.MlDsaParams) :
  ml_dsa.verify.spec K L C_TILDE_LEN W1_BYTES pk message sigma ctx params
  := by sorry

@[spec]
theorem ntt.bit_rev_8.spec.proof (m : Std.Usize) : ntt.bit_rev_8.spec m
  := by sorry

@[spec]
theorem ntt.ntt_layer.spec.proof (p : Array Std.I32 256#usize)
  (layer : Std.Usize) : ntt.ntt_layer.spec p layer
  := by sorry

@[spec]
theorem ntt.intt_layer.spec.proof (p : Array Std.I32 256#usize)
  (layer : Std.Usize) : ntt.intt_layer.spec p layer
  := by sorry

@[spec]
theorem parameters.pk_size.spec.proof (params : parameters.MlDsaParams) :
  parameters.pk_size.spec params
  := by sorry

@[spec]
theorem parameters.sk_size.spec.proof (params : parameters.MlDsaParams) :
  parameters.sk_size.spec params
  := by sorry

@[spec]
theorem parameters.sig_size.spec.proof (params : parameters.MlDsaParams) :
  parameters.sig_size.spec params
  := by sorry

@[spec]
theorem parameters.bitlen.spec.proof (n : Std.Usize) : parameters.bitlen.spec n
  := by sorry

@[spec]
theorem polynomial.vector_power2round.spec.proof {N : Std.Usize}
  (v : Array (Array Std.I32 256#usize) N) :
  polynomial.vector_power2round.spec v
  := by sorry

@[spec]
theorem polynomial.vector_high_bits.spec.proof {N : Std.Usize}
  (v : Array (Array Std.I32 256#usize) N) (gamma2 : Std.I32) :
  polynomial.vector_high_bits.spec v gamma2
  := by sorry

@[spec]
theorem polynomial.vector_low_bits.spec.proof {N : Std.Usize}
  (v : Array (Array Std.I32 256#usize) N) (gamma2 : Std.I32) :
  polynomial.vector_low_bits.spec v gamma2
  := by sorry

@[spec]
theorem polynomial.count_hints.spec.proof {N : Std.Usize}
  (h : Array (Array Bool 256#usize) N) : polynomial.count_hints.spec h
  := by sorry

@[spec]
theorem polynomial.vector_make_hint.spec.proof {N : Std.Usize}
  (z : Array (Array Std.I32 256#usize) N)
  (r : Array (Array Std.I32 256#usize) N) (gamma2 : Std.I32) :
  polynomial.vector_make_hint.spec z r gamma2
  := by sorry

@[spec]
theorem polynomial.vector_use_hint.spec.proof {N : Std.Usize}
  (h : Array (Array Bool 256#usize) N) (r : Array (Array Std.I32 256#usize) N)
  (gamma2 : Std.I32) : polynomial.vector_use_hint.spec h r gamma2
  := by sorry

@[spec]
theorem sampling.sample_in_ball.spec.proof (rho : Slice Std.U8)
  (tau : Std.Usize) : sampling.sample_in_ball.spec rho tau
  := by sorry

@[spec]
theorem sampling.expand_a.spec.proof (K : Std.Usize) (L : Std.Usize)
  (rho : Array Std.U8 32#usize) : sampling.expand_a.spec K L rho
  := by sorry

@[spec]
theorem sampling.expand_s.spec.proof (K : Std.Usize) (L : Std.Usize)
  (rho_prime : Array Std.U8 64#usize) (eta : Std.Usize) :
  sampling.expand_s.spec K L rho_prime eta
  := by sorry

@[spec]
theorem sampling.expand_mask.spec.proof (L : Std.Usize)
  (rho_pp : Array Std.U8 64#usize) (kappa : Std.Usize) (gamma1 : Std.I32) :
  sampling.expand_mask.spec L rho_pp kappa gamma1
  := by sorry

end hacspec_ml_dsa
