-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_ml_dsa]: type definitions
import Aeneas
import CoreModels
import HacspecMlDsa.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hacspec_ml_dsa

/-- [hacspec_ml_dsa::parameters::bitlen::closure]
    Source: 'ml-dsa/src/parameters.rs', lines 152:33-152:55 -/
@[reducible]
def parameters.bitlen.closure := Std.Usize

/-- [hacspec_ml_dsa::encoding::simple_bit_pack::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 25:37-25:61 -/
@[reducible]
def encoding.simple_bit_pack.closure_1 (BYTES : Std.Usize) := Std.Usize

/-- [hacspec_ml_dsa::encoding::simple_bit_pack::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 21:33-21:57 -/
@[reducible]
def encoding.simple_bit_pack.closure (BYTES : Std.Usize) := Unit

/-- [hacspec_ml_dsa::encoding::bit_pack::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 50:37-50:61 -/
@[reducible]
def encoding.bit_pack.closure_1 (BYTES : Std.Usize) := Std.Usize

/-- [hacspec_ml_dsa::encoding::bit_pack::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 46:33-46:57 -/
@[reducible]
def encoding.bit_pack.closure (BYTES : Std.Usize) := Unit

/-- [hacspec_ml_dsa::encoding::simple_bit_unpack::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 73:37-73:64 -/
@[reducible]
def encoding.simple_bit_unpack.closure_1 := Unit

/-- [hacspec_ml_dsa::encoding::simple_bit_unpack::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 69:33-69:57 -/
@[reducible]
def encoding.simple_bit_unpack.closure := Unit

/-- [hacspec_ml_dsa::encoding::bit_unpack::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 101:37-101:64 -/
@[reducible]
def encoding.bit_unpack.closure_1 := Unit

/-- [hacspec_ml_dsa::encoding::bit_unpack::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 97:33-97:57 -/
@[reducible]
def encoding.bit_unpack.closure := Unit

/-- [hacspec_ml_dsa::encoding::pk_decode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 218:38-221:5 -/
@[reducible]
def encoding.pk_decode.closure (K : Std.Usize) := Slice Std.U8

/-- [hacspec_ml_dsa::parameters::MlDsaParams]
    Source: 'ml-dsa/src/parameters.rs', lines 31:0-59:1
    Visibility: public -/
structure parameters.MlDsaParams where
  k : Std.Usize
  l : Std.Usize
  tau : Std.Usize
  lambda : Std.Usize
  gamma1 : Std.I32
  gamma2 : Std.I32
  eta : Std.Usize
  omega : Std.Usize
  beta : Std.I32

/-- [hacspec_ml_dsa::encoding::sk_encode::closure#2]
    Source: 'ml-dsa/src/encoding.rs', lines 280:12-280:81 -/
def encoding.sk_encode.closure_2 (K : Std.Usize) (L : Std.Usize) (SK_SIZE :
  Std.Usize) :=
  Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::encoding::sk_encode::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 262:12-262:94 -/
def encoding.sk_encode.closure_1 (K : Std.Usize) (L : Std.Usize) (SK_SIZE :
  Std.Usize) :=
  Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::encoding::sk_encode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 248:33-248:86 -/
def encoding.sk_encode.closure (K : Std.Usize) (L : Std.Usize) (SK_SIZE :
  Std.Usize) :=
  Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::encoding::sk_decode::closure#2]
    Source: 'ml-dsa/src/encoding.rs', lines 327:38-334:5 -/
def encoding.sk_decode.closure_2 (K : Std.Usize) (L : Std.Usize) :=
  Std.Usize × Std.Usize × Slice Std.U8 × Std.Usize

/-- [hacspec_ml_dsa::encoding::sk_decode::closure#1]
    Source: 'ml-dsa/src/encoding.rs', lines 319:38-322:5 -/
def encoding.sk_decode.closure_1 (K : Std.Usize) (L : Std.Usize) :=
  Std.Usize × Slice Std.U8 × Std.Usize

/-- [hacspec_ml_dsa::encoding::sk_decode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 315:38-318:5 -/
def encoding.sk_decode.closure (K : Std.Usize) (L : Std.Usize) :=
  Std.Usize × Slice Std.U8 × Std.Usize

/-- [hacspec_ml_dsa::encoding::sig_encode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 372:12-372:85 -/
def encoding.sig_encode.closure (K : Std.Usize) (L : Std.Usize) (SIG_SIZE :
  Std.Usize) :=
  Std.Usize × Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::encoding::sig_decode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 421:37-424:5 -/
def encoding.sig_decode.closure (K : Std.Usize) (L : Std.Usize) (C_TILDE_LEN :
  Std.Usize) :=
  Std.Usize × Slice Std.U8 × Std.Usize

/-- [hacspec_ml_dsa::encoding::w1_encode::closure]
    Source: 'ml-dsa/src/encoding.rs', lines 450:33-450:50 -/
@[reducible]
def encoding.w1_encode.closure (K : Std.Usize) (W1_BYTES : Std.Usize) := Unit

/-- [hacspec_ml_dsa::error::MlDsaError]
    Source: 'ml-dsa/src/error.rs', lines 7:0-36:1
    Visibility: public -/
@[discriminant isize]
inductive error.MlDsaError where
| SampleInBallExhausted : error.MlDsaError
| RejectionSamplingExhausted : error.MlDsaError
| MalformedSignature : error.MlDsaError
| InvalidSignature : error.MlDsaError

/-- [hacspec_ml_dsa::polynomial::poly_pointwise_mul::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 22:12-22:48 -/
def polynomial.poly_pointwise_mul.closure :=
  Array Std.I32 256#usize × Array Std.I32 256#usize

/-- [hacspec_ml_dsa::polynomial::poly_add::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 12:12-12:48 -/
def polynomial.poly_add.closure :=
  Array Std.I32 256#usize × Array Std.I32 256#usize

/-- [hacspec_ml_dsa::matrix::matrix_vector_ntt::closure]
    Source: 'ml-dsa/src/matrix.rs', lines 15:12-22:5 -/
def matrix.matrix_vector_ntt.closure (K : Std.Usize) (L : Std.Usize) :=
  Array (Array (Array Std.I32 256#usize) L) K × Array (Array Std.I32
  256#usize) L

/-- [hacspec_ml_dsa::sampling::expand_s::closure#1]
    Source: 'ml-dsa/src/sampling.rs', lines 186:38-190:5 -/
def sampling.expand_s.closure_1 (K : Std.Usize) (L : Std.Usize) :=
  Array Std.U8 64#usize × Std.Usize

/-- [hacspec_ml_dsa::sampling::expand_s::closure]
    Source: 'ml-dsa/src/sampling.rs', lines 182:38-185:5 -/
def sampling.expand_s.closure (K : Std.Usize) (L : Std.Usize) :=
  Array Std.U8 64#usize × Std.Usize

/-- [hacspec_ml_dsa::sampling::expand_a::closure::closure]
    Source: 'ml-dsa/src/sampling.rs', lines 166:16-169:9 -/
def sampling.expand_a.closure.closure (K : Std.Usize) (L : Std.Usize) :=
  Array Std.U8 32#usize × Std.Usize

/-- [hacspec_ml_dsa::sampling::expand_a::closure]
    Source: 'ml-dsa/src/sampling.rs', lines 165:12-170:5 -/
@[reducible]
def sampling.expand_a.closure (K : Std.Usize) (L : Std.Usize) :=
  Array Std.U8 32#usize

/-- [hacspec_ml_dsa::polynomial::vector_power2round::closure#1::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 95:16-98:9 -/
def polynomial.vector_power2round.closure_1.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.Usize

/-- [hacspec_ml_dsa::polynomial::vector_power2round::closure#1]
    Source: 'ml-dsa/src/polynomial.rs', lines 94:38-99:5 -/
@[reducible]
def polynomial.vector_power2round.closure_1 (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::polynomial::vector_power2round::closure::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 89:16-92:9 -/
def polynomial.vector_power2round.closure.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.Usize

/-- [hacspec_ml_dsa::polynomial::vector_power2round::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 88:38-93:5 -/
@[reducible]
def polynomial.vector_power2round.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::polynomial::vector_add::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 40:12-40:38 -/
def polynomial.vector_add.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::polynomial::vector_intt::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 32:12-32:26 -/
@[reducible]
def polynomial.vector_intt.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::ntt::reduce_polynomial::closure]
    Source: 'ml-dsa/src/ntt.rs', lines 119:12-119:38 -/
def ntt.reduce_polynomial.closure := Std.I64 × Array Std.I32 256#usize

/-- [hacspec_ml_dsa::ntt::intt_layer::closure]
    Source: 'ml-dsa/src/ntt.rs', lines 103:12-113:5 -/
def ntt.intt_layer.closure := Std.Usize × Array Std.I32 256#usize × Std.Usize

/-- [hacspec_ml_dsa::polynomial::vector_ntt::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 27:12-27:25 -/
@[reducible]
def polynomial.vector_ntt.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::ntt::ntt_layer::closure]
    Source: 'ml-dsa/src/ntt.rs', lines 64:12-75:5 -/
def ntt.ntt_layer.closure := Std.Usize × Std.Usize × Array Std.I32 256#usize

/-- [hacspec_ml_dsa::sampling::expand_mask::closure]
    Source: 'ml-dsa/src/sampling.rs', lines 207:12-217:5 -/
def sampling.expand_mask.closure (L : Std.Usize) :=
  Std.Usize × Array Std.U8 64#usize × Std.I32

/-- [hacspec_ml_dsa::sampling::sample_in_ball::closure]
    Source: 'ml-dsa/src/sampling.rs', lines 82:41-82:72 -/
def sampling.sample_in_ball.closure := Bool × Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::polynomial::vector_make_hint::closure::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 145:28-145:86 -/
def polynomial.vector_make_hint.closure.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.Usize × Array (Array Std.I32
  256#usize) N × Std.I32

/-- [hacspec_ml_dsa::polynomial::vector_make_hint::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 145:16-145:87 -/
def polynomial.vector_make_hint.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Array (Array Std.I32 256#usize) N ×
  Std.I32

/-- [hacspec_ml_dsa::polynomial::count_hints::closure#1]
    Source: 'ml-dsa/src/polynomial.rs', lines 128:37-128:68 -/
def polynomial.count_hints.closure_1 (N : Std.Usize) := Std.Usize × Std.Usize

/-- [hacspec_ml_dsa::polynomial::count_hints::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 125:33-125:60 -/
@[reducible]
def polynomial.count_hints.closure (N : Std.Usize) := Std.Usize

/-- [hacspec_ml_dsa::polynomial::vector_low_bits::closure::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 115:24-115:72 -/
def polynomial.vector_low_bits.closure.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.Usize × Std.I32

/-- [hacspec_ml_dsa::polynomial::vector_low_bits::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 115:12-115:73 -/
def polynomial.vector_low_bits.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.I32

/-- [hacspec_ml_dsa::polynomial::vector_high_bits::closure::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 109:24-109:73 -/
def polynomial.vector_high_bits.closure.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.Usize × Std.I32

/-- [hacspec_ml_dsa::polynomial::vector_high_bits::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 109:12-109:74 -/
def polynomial.vector_high_bits.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Std.I32

/-- [hacspec_ml_dsa::polynomial::scalar_vector_ntt::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 56:12-56:44 -/
def polynomial.scalar_vector_ntt.closure (N : Std.Usize) :=
  Array Std.I32 256#usize × Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::polynomial::vector_sub::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 48:12-48:38 -/
def polynomial.vector_sub.closure (N : Std.Usize) :=
  Array (Array Std.I32 256#usize) N × Array (Array Std.I32 256#usize) N

/-- [hacspec_ml_dsa::polynomial::poly_sub::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 17:12-17:48 -/
def polynomial.poly_sub.closure :=
  Array Std.I32 256#usize × Array Std.I32 256#usize

/-- [hacspec_ml_dsa::polynomial::poly_mod_pm::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 163:12-171:5 -/
@[reducible]
def polynomial.poly_mod_pm.closure := Array Std.I32 256#usize

/-- [hacspec_ml_dsa::ml_dsa::try_sign_iteration::closure#1]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 208:46-208:68 -/
@[reducible]
def ml_dsa.try_sign_iteration.closure_1 (K : Std.Usize) (L : Std.Usize)
  (SIG_SIZE : Std.Usize) (W1_BYTES : Std.Usize) (C_TILDE_LEN : Std.Usize) :=
  Array (Array Std.I32 256#usize) L

/-- [hacspec_ml_dsa::ml_dsa::try_sign_iteration::closure]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 189:43-195:5 -/
@[reducible]
def ml_dsa.try_sign_iteration.closure (K : Std.Usize) (L : Std.Usize) (SIG_SIZE
  : Std.Usize) (W1_BYTES : Std.Usize) (C_TILDE_LEN : Std.Usize) :=
  Array (Array Std.I32 256#usize) K

/-- [hacspec_ml_dsa::polynomial::vector_use_hint::closure::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 157:24-157:81 -/
def polynomial.vector_use_hint.closure.closure (N : Std.Usize) :=
  Array (Array Bool 256#usize) N × Std.Usize × Array (Array Std.I32
  256#usize) N × Std.I32

/-- [hacspec_ml_dsa::polynomial::vector_use_hint::closure]
    Source: 'ml-dsa/src/polynomial.rs', lines 157:12-157:82 -/
def polynomial.vector_use_hint.closure (N : Std.Usize) :=
  Array (Array Bool 256#usize) N × Array (Array Std.I32 256#usize) N ×
  Std.I32

/-- [hacspec_ml_dsa::ml_dsa::verify_internal::closure#2]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 369:36-369:92 -/
def ml_dsa.verify_internal.closure_2 (K : Std.Usize) (L : Std.Usize)
  (C_TILDE_LEN : Std.Usize) (W1_BYTES : Std.Usize) :=
  Array (Array Std.I32 256#usize) K × Array (Array Std.I32 256#usize) K

/-- [hacspec_ml_dsa::ml_dsa::verify_internal::closure#1]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 365:63-367:25 -/
def ml_dsa.verify_internal.closure_1 (K : Std.Usize) (L : Std.Usize)
  (C_TILDE_LEN : Std.Usize) (W1_BYTES : Std.Usize) :=
  Array Std.I32 256#usize × Array (Array Std.I32 256#usize) K

/-- [hacspec_ml_dsa::ml_dsa::verify_internal::closure::closure]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 363:48-363:89 -/
def ml_dsa.verify_internal.closure.closure (K : Std.Usize) (L : Std.Usize)
  (C_TILDE_LEN : Std.Usize) (W1_BYTES : Std.Usize) :=
  Array (Array Std.I32 256#usize) K × Std.Usize × Std.I32

/-- [hacspec_ml_dsa::ml_dsa::verify_internal::closure]
    Source: 'ml-dsa/src/ml_dsa.rs', lines 363:36-363:90 -/
def ml_dsa.verify_internal.closure (K : Std.Usize) (L : Std.Usize) (C_TILDE_LEN
  : Std.Usize) (W1_BYTES : Std.Usize) :=
  Array (Array Std.I32 256#usize) K × Std.I32

end hacspec_ml_dsa
