-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_ml_dsa]: external functions.
-- Hand-written external models (mirrors the ml-kem spec's FunsExternal). The
-- CoreModels library (hax-lean v0.2.0) provides most bridges natively; only the
-- still-missing ones are added below.
import Aeneas
import CoreModels
import HacspecMlDsa.Extraction.Types
import HacspecSha3.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 2048
open hacspec_ml_dsa

noncomputable section

namespace CoreModels.core

end CoreModels.core

-- The hash-function entry points are external as of cargo-hax 0.4 (the 0.3.7
-- extraction emitted no models for them). Copied verbatim from the generated
-- `Extraction/FunsExternal_Template.lean`.
/-- [hacspec_ml_dsa::hash_functions::h]:
    Source: 'ml-dsa/src/hash_functions.rs', lines 9:0-11:1 -/
axiom hash_functions.h
  (N : Std.Usize) : Slice Std.U8 → RustM (Array Std.U8 N)

/-- [hacspec_ml_dsa::hash_functions::g]:
    Source: 'ml-dsa/src/hash_functions.rs', lines 16:0-18:1 -/
axiom hash_functions.g
  (N : Std.Usize) : Slice Std.U8 → RustM (Array Std.U8 N)

/-- [hacspec_ml_dsa::hash_functions::h2]:
    Source: 'ml-dsa/src/hash_functions.rs', lines 23:0-27:1 -/
axiom hash_functions.h2
  (N : Std.Usize) : Slice Std.U8 → Slice Std.U8 → RustM (Array Std.U8 N)

/-- `hax_lib::loop_invariant!` marker. cargo-hax 0.4 emits calls to
    `hax_lib._internal_loop_invariant`, but neither hax-lean v0.3.12 nor the
    generated template declares it, so the extraction does not typecheck without
    a local model. The marker carries no computational content -- it is a proof
    hint -- so modelling it as a no-op is sound for this spec package. Drop this
    once hax-lean ships the symbol. -/
axiom hax_lib._internal_loop_invariant
  {Into Inv State : Type} : Into → Inv → State → RustM Unit

end
