/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/mfr6l75nil9phxx3lrg4al56qrdp94g6-ocaml4.14.1-eurydice-dirty/eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef __Eurydice_H
#define __Eurydice_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "core.h"
#include "eurydice_glue.h"

extern uint8_t Eurydice_bitand_pv_u8(uint8_t *x, uint8_t y);

extern uint8_t Eurydice_shr_pv_u8(uint8_t *x, int32_t y);

#if defined(__cplusplus)
}
#endif

#define __Eurydice_H_DEFINED
#endif
