/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/franziskus/eurydice//eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc
  F* version: <unknown>
  KaRaMeL version: 04cb86b9
 */

#ifndef __libcrux_sha3_neon_H
#define __libcrux_sha3_neon_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"

extern void libcrux_sha3_neon_sha512(Eurydice_slice x0, Eurydice_slice x1);

extern void libcrux_sha3_neon_sha256(Eurydice_slice x0, Eurydice_slice x1);

extern void
libcrux_sha3_neon_x2_shake256(
  Eurydice_slice x0,
  Eurydice_slice x1,
  Eurydice_slice x2,
  Eurydice_slice x3
);

extern libcrux_sha3_neon_x2_incremental_KeccakState2
libcrux_sha3_neon_x2_incremental_shake128_init(void);

extern void
libcrux_sha3_neon_x2_incremental_shake128_absorb_final(
  libcrux_sha3_neon_x2_incremental_KeccakState2 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2
);

extern void
libcrux_sha3_neon_x2_incremental_shake128_squeeze_next_block(
  libcrux_sha3_neon_x2_incremental_KeccakState2 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2
);

extern void
libcrux_sha3_neon_x2_incremental_shake128_squeeze_first_three_blocks(
  libcrux_sha3_neon_x2_incremental_KeccakState2 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2
);

#if defined(__cplusplus)
}
#endif

#define __libcrux_sha3_neon_H_DEFINED
#endif
