/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc ../../libcrux_sha3.llbc
  F* version: 58c915a8
  KaRaMeL version: 04cb86b9
 */

#ifndef __libcrux_mlkem_sha3_H
#define __libcrux_mlkem_sha3_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"

#define LIBCRUX_ML_KEM_HASH_FUNCTIONS_BLOCK_SIZE ((size_t)168U)

#define LIBCRUX_ML_KEM_HASH_FUNCTIONS_THREE_BLOCKS (LIBCRUX_ML_KEM_HASH_FUNCTIONS_BLOCK_SIZE * (size_t)3U)

#if defined(__cplusplus)
}
#endif

#define __libcrux_mlkem_sha3_H_DEFINED
#endif
