/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /nix/store/c9m211bm84ncjmaxx27ki9dymd4qkwm2-ocaml4.14.1-eurydice-dirty/eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef __libcrux_mlkem_sha3_H
#define __libcrux_mlkem_sha3_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"

#define LIBCRUX_ML_KEM_HASH_FUNCTIONS_BLOCK_SIZE ((size_t)168U)

#define LIBCRUX_ML_KEM_HASH_FUNCTIONS_THREE_BLOCKS (LIBCRUX_ML_KEM_HASH_FUNCTIONS_BLOCK_SIZE * (size_t)3U)

typedef struct libcrux_ml_kem_hash_functions_neon_Simd128Hash_s
{ libcrux_sha3_neon_x2_incremental_KeccakState2 shake128_state[2U]; }
libcrux_ml_kem_hash_functions_neon_Simd128Hash;

#if defined(__cplusplus)
}
#endif

#define __libcrux_mlkem_sha3_H_DEFINED
#endif
