/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc ../../libcrux_sha3.llbc
  F* version: 58c915a8
  KaRaMeL version: 5666a5de
 */

#ifndef __internal_libcrux_sha3_H
#define __internal_libcrux_sha3_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "internal/libcrux_core.h"
#include "../libcrux_sha3.h"
#include "eurydice_glue.h"

static const
uint64_t
libcrux_sha3_generic_keccak_ROUNDCONSTANTS[24U] =
  {
    1ULL, 32898ULL, 9223372036854808714ULL, 9223372039002292224ULL, 32907ULL, 2147483649ULL,
    9223372039002292353ULL, 9223372036854808585ULL, 138ULL, 136ULL, 2147516425ULL, 2147483658ULL,
    2147516555ULL, 9223372036854775947ULL, 9223372036854808713ULL, 9223372036854808579ULL,
    9223372036854808578ULL, 9223372036854775936ULL, 32778ULL, 9223372039002259466ULL,
    9223372039002292353ULL, 9223372036854808704ULL, 2147483649ULL, 9223372039002292232ULL
  };

libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t
libcrux_sha3_generic_keccak__libcrux_sha3__generic_keccak__KeccakState_T__N__TraitClause_0__1__new__uint64_t_1size_t(
  void
);

void
libcrux_sha3_portable_keccakx1___136size_t_31uint8_t(
  Eurydice_slice data[1U],
  Eurydice_slice out[1U]
);

static inline void libcrux_sha3_portable_shake256(Eurydice_slice digest, Eurydice_slice data)
{
  Eurydice_slice buf0[1U] = { data };
  Eurydice_slice buf[1U] = { digest };
  libcrux_sha3_portable_keccakx1___136size_t_31uint8_t(buf0, buf);
}

static inline libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t
libcrux_sha3_portable_incremental_shake128_init(void)
{
  return
    libcrux_sha3_generic_keccak__libcrux_sha3__generic_keccak__KeccakState_T__N__TraitClause_0__1__new__uint64_t_1size_t();
}

void
libcrux_sha3_generic_keccak_absorb_final__uint64_t_1size_t_168size_t_31uint8_t(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice last[1U]
);

static inline void
libcrux_sha3_portable_incremental_shake128_absorb_final(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice data0
)
{
  Eurydice_slice buf[1U] = { data0 };
  libcrux_sha3_generic_keccak_absorb_final__uint64_t_1size_t_168size_t_31uint8_t(s, buf);
}

void
libcrux_sha3_generic_keccak_squeeze_next_block__uint64_t_1size_t_168size_t(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice out[1U]
);

static inline void
libcrux_sha3_portable_incremental_shake128_squeeze_next_block(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice out0
)
{
  Eurydice_slice buf[1U] = { out0 };
  libcrux_sha3_generic_keccak_squeeze_next_block__uint64_t_1size_t_168size_t(s, buf);
}

void
libcrux_sha3_generic_keccak_squeeze_first_three_blocks__uint64_t_1size_t_168size_t(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice out[1U]
);

static inline void
libcrux_sha3_portable_incremental_shake128_squeeze_first_three_blocks(
  libcrux_sha3_generic_keccak_KeccakState__uint64_t__1size_t *s,
  Eurydice_slice out0
)
{
  Eurydice_slice buf[1U] = { out0 };
  libcrux_sha3_generic_keccak_squeeze_first_three_blocks__uint64_t_1size_t_168size_t(s, buf);
}

#if defined(__cplusplus)
}
#endif

#define __internal_libcrux_sha3_H_DEFINED
#endif
