name: ECDH - Build & Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/rust-build-test.yml
    with:
      working-directory: libcrux-ecdh
      intel-mac: true
      no-std-crate: libcrux-ecdh
      no-std-extra-flags: --no-default-features
