name: HPKE - iOS

on:
  pull_request:
    # Run only when something changes in hpke-rs, or its direct workspace dependencies
    paths:
      - 'crates/protocols/hpke/**'
      - 'crates/algorithms/sha3/**/*.rs'
      - 'libcrux-ecdh/**/*.rs'
      - 'crates/algorithms/hkdf/**/*.rs'
      - 'crates/primitives/aead/**/*.rs'
      - 'libcrux-kem/**/*.rs'
      - 'traits/**/*.rs'


env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./crates/protocols/hpke

jobs:
  build:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Setup MacOS
      run: |
        rustup target install aarch64-apple-darwin
        rustup target install aarch64-apple-ios
    - name: Apple Silicon Build
      run: |
        cargo build --target aarch64-apple-darwin --tests --verbose
        cargo build --release --target aarch64-apple-darwin --tests --verbose
    - name: iOS build
      run: |
        cargo build --target aarch64-apple-ios --tests --verbose
        cargo build --release --target aarch64-apple-ios --tests --verbose
