name: ML-KEM - hax

on:
  merge_group:
  push:
    branches: ["dev", "main"]

  pull_request:
    branches: ["dev", "main"]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  FSTAR_REV: v2026.03.24
  HAX_LIB_VERSION: 0.3.7

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: hacspec/hax-actions@main
        with:
          hax_reference: v${{ HAX_LIB_VERSION }}
          fstar: $FSTAR_REV
          
      - name: Use precise version of hax-lib
        run: cargo update hax-lib --precise $HAX_LIB_VERSION

      - name: 🏃 Extract ML-KEM crate
        working-directory: libcrux-ml-kem
        run: ./hax.py extract

      - name: ↑ Upload F* extraction
        uses: actions/upload-artifact@v7
        with:
          name: fstar-extractions
          path: "**/proofs/fstar"
          include-hidden-files: true
          if-no-files-found: error

  lax:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'merge_group' }}
    needs:
      - extract

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: hacspec/hax-actions@main
        with:
          hax_reference: v${{ HAX_LIB_VERSION }}
          fstar: $FSTAR_REV
          
      - name: Use precise version of hax-lib
        run: cargo update hax-lib --precise $HAX_LIB_VERSION

      - uses: actions/download-artifact@v8
        with:
          name: fstar-extractions
          path: .
      - name: 🏃 Lax ML-KEM crate
        working-directory: libcrux-ml-kem
        run: ./hax.py prove --admit
        
  # XXX: Is the caching performed by hacspec/hax-actions enough to get CI minutes down for paid runners?
  # prove:
  #   runs-on: #TODO
  #   if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
  #   needs:
  #     - extract
  #   steps:
  #     - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
  #     - uses: hacspec/hax-actions@main
  #       with:
  #         hax_reference: v${{ HAX_LIB_VERSION }}
  #         fstar: $FSTAR_REV
          
  #     - name: Use precise version of hax-lib
  #       run: cargo update hax-lib --precise $HAX_LIB_VERSION
      
  #     - uses: actions/download-artifact@v8
  #       with:
  #         name: fstar-extractions
  #         path: .

  #     - name: 🏃 Prove ML-KEM crate
  #       working-directory: libcrux-ml-kem
  #       run: FSTAR_HOME=~/.nix-profile ./hax.py prove
  
  mlkem-extract-hax-status:
    if: ${{ always() }}
    needs: [extract]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
  
  mlkem-lax-hax-status:
    if: ${{ always() }}
    needs: [lax]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
