name: Libcrux - no_std Check

on:
  merge_group:
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  no-std-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        run: rustup target add thumbv7em-none-eabihf

      - name: Check no_std compatibility
        run: |
          ./no-std-check.sh
