name: Platform - Build & Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  platform:
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        os:
          - macos-15-intel # Intel mac
          - macos-latest # macos-15 on apple silicon
          - ubuntu-latest
          - windows-latest
        exclude:
          - bits: 32
            os: "macos-latest"
          - bits: 32
            os: "macos-15-intel"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: crates/sys/platform

    steps:
      - uses: actions/checkout@v6

      - name: Update dependencies
        run: cargo update

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 🏃🏻‍♀️ Test
        run: cargo test --verbose -- --nocapture

      - name: 🏃🏻‍♀️ Test Release
        run: cargo test --verbose --release -- --nocapture

      - name: 🛠️ Setup Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🏃🏻‍♀️ Test Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: cargo test --verbose --target i686-unknown-linux-gnu -- --nocapture

      - name: 🏃🏻‍♀️ Test Release Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: cargo test --verbose --release --target i686-unknown-linux-gnu -- --nocapture

      - name: 🏃🏻‍♀️ Test Windows x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'windows-latest' }}
        run: cargo test --verbose --target i686-pc-windows-msvc -- --nocapture

      - name: 🏃🏻‍♀️ Test Release Windows x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'windows-latest' }}
        run: cargo test --verbose --release --target i686-pc-windows-msvc -- --nocapture

  build-no_std:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: crates/sys/platform

    steps:
      - uses: actions/checkout@v6

      - name: Add no_std target
        run: rustup target add thumbv6m-none-eabi

      - name: Update dependencies
        run: cargo update

      - name: 🔨 Build
        run: |
          rustc --print=cfg
          cargo check --lib --verbose --target thumbv6m-none-eabi
