name: secrets - Build & Test

on:
  merge_group:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'merge_group' }}
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        os:
          - macos-15-intel # Intel mac
          - macos-latest # macos-14 m1
          - ubuntu-latest
          - windows-latest
        exclude:
          - bits: 32
            os: "macos-latest"
          - bits: 32
            os: "macos-15-intel"
          - bits: 32 # FIXME: Linking isn't working here yet for hacl #42
            os: "windows-latest"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: crates/utils/secrets

    steps:
      - uses: actions/checkout@v6

      - run: echo "RUST_TARGET_FLAG=" > $GITHUB_ENV
        if: ${{ matrix.bits == 64 }}

      - name: 🛠️ Setup Rust Nightly
        run: rustup toolchain install nightly

      - name: 🛠️ Setup Ubuntu x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🛠️ Setup Ubuntu x64
        if: ${{ matrix.bits == 64 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add aarch64-unknown-linux-gnu

      # Set up 32 bit systems

      - name: 🛠️ Config Windows x86
        run: echo "RUST_TARGET_FLAG=--target=i686-pc-windows-msvc" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'windows-latest' }}

      - name: 🛠️ Config Linux x86
        run: |
          echo "RUST_TARGET_FLAG=--target=i686-unknown-linux-gnu" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'ubuntu-latest' }}

      # Build ...

      - name: 🔨 Build
        run: |
          rustc --print=cfg
          cargo build --verbose $RUST_TARGET_FLAG

      - name: 🔨 Build Release
        run: cargo build --verbose --release $RUST_TARGET_FLAG

      - name: 🏃🏻 Asan MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: RUSTDOCFLAGS=-Zsanitizer=address RUSTFLAGS=-Zsanitizer=address cargo +nightly test --release --target aarch64-apple-darwin

      # - name: ⬆ Upload build
      #   uses: ./.github/actions/upload_artifacts
      #   with:
      #     name: build_${{ matrix.os }}_${{ matrix.bits }}

      # Test ...

      - name: 🏃🏻‍♀️ Test
        run: |
          cargo clean
          cargo test --verbose $RUST_TARGET_FLAG

      - name: 🏃🏻‍♀️ Test Release
        run: |
          cargo clean
          cargo test --verbose --release $RUST_TARGET_FLAG

      - name: 🏃🏻‍♀️ Test Secret Independence
        run: |
          cargo clean
          cargo test --verbose $RUST_TARGET_FLAG --features check-secret-independence

      - name: 🏃🏻‍♀️ Test Release Secret Independence
        run: |
          cargo clean
          cargo test --verbose --release $RUST_TARGET_FLAG --features check-secret-independence
          
      - name: 🏃🏻‍♀️ Test Portable
        run: |
          cargo clean
          LIBCRUX_DISABLE_SIMD128=1 LIBCRUX_DISABLE_SIMD256=1 cargo test --verbose $RUST_TARGET_FLAG

      - name: 🏃🏻‍♀️ Test Portable Release
        run: |
          cargo clean
          LIBCRUX_DISABLE_SIMD128=1 LIBCRUX_DISABLE_SIMD256=1 cargo test --verbose --release $RUST_TARGET_FLAG

  build-no_std:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: crates/utils/secrets

    steps:
      - uses: actions/checkout@v7

      - name: Add no_std target
        run: rustup target add thumbv6m-none-eabi

      - name: 🔨 Check
        run: cargo check --lib --verbose --target thumbv6m-none-eabi

      - name: 🔨 Check with --features check-secret-independence
        run: cargo check --lib --verbose --target thumbv6m-none-eabi --features check-secret-independence

  valgrind-ct-test:
    if: ${{ github.event_name != 'merge_group' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
        features:
          - ""
          - "--features check-secret-independence"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: crates/utils/secrets
    env:
      RUSTFLAGS: '--cfg valgrind_ct_test'
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: 'valgrind --tool=memcheck --error-exitcode=1 --track-origins=yes'
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER: 'valgrind --tool=memcheck --error-exitcode=1 --track-origins=yes'

    steps:
      - uses: actions/checkout@v6

      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: 🏃🏻‍♀️ Test under valgrind
        run: cargo test --verbose --profile release-debug ${{ matrix.features }}

  secrets-build-test-status:
    if: ${{ always() }}
    needs: [build, valgrind-ct-test]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
